/**
 * ESLint 10, flat config, type-aware.
 *
 * The presets do the work. Everything listed by hand below is either a rule that has to
 * be tuned for a framework-free codebase that builds its own DOM, or one of the handful of
 * import rules that tell you something the compiler cannot.
 */

import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';
import unicorn from 'eslint-plugin-unicorn';
import importX from 'eslint-plugin-import-x';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import regexp from 'eslint-plugin-regexp';
import noUnsanitized from 'eslint-plugin-no-unsanitized';
import vitest from '@vitest/eslint-plugin';

export default defineConfig([
  // `api.d.ts` is generated by `pnpm codegen` and is not ours to lint.
  globalIgnores([
    'dist',
    'coverage',
    'playwright-report',
    'test-results',
    'src/types/api.d.ts',
    // Agent tooling scratch, gitignored at the repo root and regenerated by a save hook,
    // so deleting it does not stop it coming back. Without this the type-aware parser
    // fails on a file outside `tsconfig.json` and takes the whole gate down with it.
    '.remember',
  ]),

  {
    linterOptions: {
      // Native in ESLint 10, so no eslint-comments plugin is needed. A disable comment
      // that stopped suppressing anything is a lie about the code and fails the build.
      reportUnusedDisableDirectives: 'error',
      reportUnusedInlineConfigs: 'error',
    },
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      'import-x/resolver-next': [createTypeScriptImportResolver()],
    },
  },

  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  unicorn.configs.recommended,
  regexp.configs['flat/recommended'],
  noUnsanitized.configs.recommended,

  {
    // The import-x preset is skipped deliberately: almost every rule in it restates
    // something `tsc` already proves, and each one costs resolver time. These four are
    // the ones that earn it, `no-cycle` above all: TypeScript resolves circular imports
    // happily and then the bundle evaluates them in an order that leaves a binding
    // undefined at runtime.
    plugins: { 'import-x': importX },
    rules: {
      'import-x/no-cycle': ['error', { maxDepth: Infinity }],
      'import-x/no-duplicates': 'error',
      'import-x/no-extraneous-dependencies': 'error',
      'import-x/consistent-type-specifier-style': ['error', 'prefer-top-level'],

      '@typescript-eslint/consistent-type-imports': 'error',
      // Without allowNumber every `${count}` in a template string is an error, and this
      // codebase builds its DOM text by hand.
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      '@typescript-eslint/no-unnecessary-condition': [
        'error',
        { allowConstantLoopConditions: 'only-allowed-literals' },
      ],

      // In unicorn 73 the rule is `name-replacements`; `prevent-abbreviations` still
      // resolves as a deprecated alias, so switching that name off is a silent no-op.
      // Off because the domain abbreviations here (lon, lat, ms, deg) are the correct
      // names for what they hold.
      'unicorn/name-replacements': 'off',
      // The contract distinguishes null (reported as absent) from undefined (not present
      // in the payload at all), and the DOM APIs used here return null.
      'unicorn/no-null': 'off',
      // `window` is the correct receiver in a browser-only bundle, and `globalThis` reads
      // as if this code might run under Node.
      'unicorn/prefer-global-this': 'off',
      // Off: it would rewrite roughly forty one-line JSDoc comments into three-line
      // blocks. Pure churn, and it makes short doc comments harder to scan, not easier.
      'unicorn/single-line-block-comment-style': 'off',
      // Off: `inEmergency` and `onGround` deliberately mirror the backend contract fields
      // `in_emergency` and `on_ground` (see the note at the top of src/domain/derive.ts).
      // Renaming them to `isInEmergency` would break exactly the parity that comment is
      // there to protect, and the rule cannot tell a mirrored name from a careless one.
      'unicorn/consistent-boolean-name': 'off',
      // Off: it wants every private helper hoisted above the public method it serves.
      // These classes are written public API first, which is the order a reader needs.
      'unicorn/consistent-class-member-order': 'off',

      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },

  {
    files: ['**/*.test.ts', 'e2e/**/*.ts'],
    extends: [vitest.configs.recommended],
    rules: {
      // A stray `.only` silently skips the rest of the suite while CI still goes green.
      'vitest/no-focused-tests': 'error',
      'vitest/no-disabled-tests': 'error',
      'vitest/expect-expect': 'error',
      // A test asserting on a value it has just constructed knows it is there.
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  {
    files: ['*.config.ts', '*.config.js', '*.config.mjs', 'eslint.config.js'],
    extends: [tseslint.configs.disableTypeChecked],
    rules: { 'import-x/no-extraneous-dependencies': 'off' },
  },
]);
