/**
* Mission Dossier & Intel Package Exporter.
*
* Compiles real-time spatial intelligence, active contact telemetry,
* perimeter geofence status, and weather observations into structured briefing
* packages (Markdown, JSON, and print-ready dossiers).
*/

/**
 * Generate formatted Markdown intelligence briefing dossier.
 * @param {object} params
 * @returns {string} Markdown text
 */
export function generateMarkdownDossier({
  operationName = "GOD'S EYE VIEW TACTICAL DOSSIER",
  classification = 'TOP SECRET // NOFORN // GEOSPATIAL INTEL',
  timestamp = new Date(),
  cameraState = {},
  trackedEntity = null,
  geofences = [],
  weather = {},
} = {}) {
  const zuluTime =
    new Date(timestamp).toISOString().replace('T', ' ').slice(0, 19) + 'Z';

  let md = `# 🛰️ ${operationName}\n\n`;
  md += `**CLASSIFICATION:** \`${classification}\`  \n`;
  md += `**TIMESTAMP (ZULU):** \`${zuluTime}\`  \n`;
  md += `**SYSTEM:** God's Eye View OSINT & Satellite Reconnaissance Console\n\n`;
  md += `---\n\n`;

  // Camera Recon Standoff
  md += `## 📍 1. CAMERA RECON STANDOFF\n\n`;
  md += `| Parameter | Value |\n|---|---|\n`;
  md += `| Latitude | \`${cameraState.latDeg?.toFixed(5) || '0.00000'}°\` |\n`;
  md += `| Longitude | \`${cameraState.lonDeg?.toFixed(5) || '0.00000'}°\` |\n`;
  md += `| Altitude (MSL) | \`${Math.round(cameraState.altitudeM || 0).toLocaleString()} m\` |\n`;
  md += `| Heading | \`${Math.round(cameraState.headingDeg || 0)}°\` |\n`;
  md += `| Pitch | \`${Math.round(cameraState.pitchDeg || 0)}°\` |\n\n`;

  // Tracked Target Entity
  md += `## 🎯 2. TRACKED CONTACT TELEMETRY\n\n`;
  if (trackedEntity) {
    const id = trackedEntity.id || trackedEntity.callsign || 'TARGET';
    const type = trackedEntity.type || trackedEntity.category || 'AIRCRAFT';
    md += `| Metric | Telemetry |\n|---|---|\n`;
    md += `| Callsign / Identifier | **\`${id}\`** |\n`;
    md += `| Category | \`${type}\` |\n`;
    md += `| Ground Speed | \`${Math.round(trackedEntity.speedKts || 0)} kts\` |\n`;
    md += `| Barometric Altitude | \`${Math.round(trackedEntity.altitudeM || 0).toLocaleString()} m\` |\n`;
    md += `| True Heading | \`${Math.round(trackedEntity.headingDeg || 0)}°\` |\n`;
    md += `| Target Coordinates | \`${trackedEntity.latDeg?.toFixed(4)}°, ${trackedEntity.lonDeg?.toFixed(4)}°\` |\n\n`;
  } else {
    md += `*No contact currently locked into primary tracking gate.*\n\n`;
  }

  // Active Perimeter Geofences
  md += `## 🔲 3. PERIMETER GEOFENCES & BREACH AUDIT\n\n`;
  if (geofences && geofences.length) {
    md += `| Zone Name | Type | Radius / Bounds | Alert Level |\n|---|---|---|---|\n`;
    for (const z of geofences) {
      const radius = z.radiusM
        ? `${Math.round(z.radiusM / 1000)} km`
        : `${z.vertices?.length || 0} vertices`;
      md += `| **${z.name}** | \`${z.type}\` | ${radius} | \`${z.alertLevel.toUpperCase()}\` |\n`;
    }
    md += `\n`;
  } else {
    md += `*No active perimeter boundaries armed.*\n\n`;
  }

  // Atmospheric Observations
  md += `## 🌩️ 4. ATMOSPHERIC CONDITIONS\n\n`;
  if (weather && weather.available !== false) {
    md += `| Parameter | Reading |\n|---|---|\n`;
    md += `| Cloud Cover | \`${Math.round((weather.cloud || 0) * 100)}%\` |\n`;
    md += `| Precipitation | \`${weather.rain > 0 ? 'Rain' : weather.snow > 0 ? 'Snow' : 'Clear'}\` |\n`;
    md += `| Wind Vector | \`${Math.round(weather.windDirectionDeg || 0)}° @ ${Math.round((weather.wind || 0) * 80)} kph\` |\n`;
    md += `| Storm Alert | \`${weather.storm > 0.2 ? 'ACTIVE' : 'NOMINAL'}\` |\n\n`;
  } else {
    md += `*Atmospheric observation telemetry unavailable for current sector.*\n\n`;
  }

  md += `---\n*Generated by God's Eye View Intel Package Exporter — Unclassified Summary.*`;
  return md;
}

/**
 * Trigger browser file download of string content.
 */
export function downloadFile(filename, content, mimeType = 'text/plain') {
  if (typeof document === 'undefined') return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
