/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/aircraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Aircraft
         * @description Aircraft currently known to the server.
         *
         *     Military aircraft are held in their own store because they come from a separate
         *     worldwide endpoint rather than the viewport query, and merging them into one store
         *     would let a global feed evict the local one every poll.
         */
        get: operations["list_aircraft_api_aircraft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aircraft/{icao24}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Aircraft
         * @description One aircraft by ICAO address, from either store. ``null`` when not currently seen.
         */
        get: operations["get_aircraft_api_aircraft__icao24__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Which layers this deployment can serve, and the attributions it must display.
         *
         *     The Cesium ion token is returned to the browser deliberately: it is a client-side
         *     token by design, scoped to the assets it can stream, unlike the feed keys which never
         *     leave the server.
         */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and upstream feed health.
         *
         *     Reports ``ok`` whenever the process is serving, even with every feed down, because
         *     this is a liveness probe rather than a data-quality judgement. Feed trouble is
         *     visible in ``feeds`` and is what the UI banners read.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer Summary
         * @description Entity counts per layer plus upstream health, for the layer rail.
         */
        get: operations["layer_summary_api_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aircraft
         * @description One aircraft as last reported by an ADS-B feed.
         *
         *     Immutable. The store replaces the whole object on each update rather than mutating,
         *     so a snapshot handed to the API or the WebSocket hub can never change underneath its
         *     reader.
         */
        Aircraft: {
            /** @default unknown */
            aircraft_class: components["schemas"]["AircraftClass"];
            /** Barometric Altitude M */
            barometric_altitude_m?: number | null;
            /**
             * Callsign
             * @description Flight identifier as broadcast, whitespace stripped.
             */
            callsign?: string | null;
            /**
             * Category
             * @description ADS-B emitter category, e.g. A3 for a large aeroplane.
             */
            category?: string | null;
            /** @default none */
            emergency: components["schemas"]["EmergencyState"];
            /** Geometric Altitude M */
            geometric_altitude_m?: number | null;
            /** Ground Speed Mps */
            ground_speed_mps?: number | null;
            /**
             * Icao24
             * @description 24-bit ICAO address, lowercase hex. The stable identity of the transponder.
             */
            icao24: string;
            /**
             * Is Military
             * @default false
             */
            is_military: boolean;
            /**
             * Kind
             * @default aircraft
             * @constant
             */
            kind: "aircraft";
            /**
             * Message Source
             * @description How the position was derived, verbatim from the feed: adsb_icao is a direct broadcast, mlat is multilaterated and less accurate, tisb_icao is rebroadcast ground data. Surfaced so the UI can be honest about accuracy.
             * @default unknown
             */
            message_source: string;
            /**
             * Messages Received
             * @default 0
             */
            messages_received: number;
            /**
             * Non Icao Address
             * @description The feed marked this address with a '~' prefix, meaning it is not a real ICAO allocation (typically a TIS-B ground vehicle or an ADS-R relay). The address is still a usable identity but should not be treated as an aircraft registration key.
             * @default false
             */
            non_icao_address: boolean;
            /**
             * Observed At
             * Format: date-time
             * @description When the feed generated the response carrying this record.
             */
            observed_at: string;
            /**
             * On Ground
             * @description True when the feed reported altitude as 'ground' rather than a number.
             * @default false
             */
            on_ground: boolean;
            /** Operator */
            operator?: string | null;
            /** Owner */
            owner?: string | null;
            point: components["schemas"]["Point"];
            /**
             * Position Age S
             * @description Seconds between the position fix and observed_at, as reported by the feed's seen_pos. Drives the stale badge in the UI.
             */
            position_age_s: number;
            /** Registered Country */
            registered_country?: string | null;
            /**
             * Registration
             * @description Tail number, from the feed's aircraft database rather than the air.
             */
            registration?: string | null;
            /**
             * Source
             * @description Which adapter produced this record, e.g. adsb.lol. Shown as attribution.
             */
            source: string;
            /** Squawk */
            squawk?: string | null;
            /**
             * Track Deg
             * @description True track over ground. Resolved from track, true_heading, mag_heading or dir, in that order of preference.
             */
            track_deg?: number | null;
            /**
             * Type Designator
             * @description ICAO type designator, e.g. B38M, GLF6, H60.
             */
            type_designator?: string | null;
            /**
             * Uses Privacy Address
             * @description Aircraft is broadcasting a privacy ICAO address. Not resolvable to an owner by design; we do not attempt to unmask it.
             * @default false
             */
            uses_privacy_address: boolean;
            /**
             * Vertical Rate Mps
             * @description Bounds are deliberately wider than any real aircraft. Live feeds emit glitch values (a -32,640 ft/min record appeared in the 2026-08-19 military sample); those must validate and be visible, not silently drop the aircraft.
             */
            vertical_rate_mps?: number | null;
        };
        /**
         * AircraftClass
         * @description How we classify an aircraft for display purposes.
         *
         *     Derived, not broadcast. ``MILITARY`` comes from the feed's own database flag;
         *     ``BUSINESS_JET`` from the type designator; ``ANONYMOUS`` marks an aircraft using a
         *     privacy ICAO address, which we display as anonymous by design and never attempt to
         *     resolve to an owner.
         * @enum {string}
         */
        AircraftClass: "unknown" | "commercial" | "business_jet" | "general_aviation" | "military" | "helicopter" | "anonymous";
        /**
         * AircraftSnapshot
         * @description Every aircraft currently held, optionally filtered to a viewport.
         */
        AircraftSnapshot: {
            /** Aircraft */
            aircraft: components["schemas"]["Aircraft"][];
            /** Count */
            count: number;
        };
        /**
         * AttributionEntry
         * @description One licence credit the UI is required to display.
         */
        AttributionEntry: {
            /** Licence */
            licence: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /** Url */
            url: string;
        };
        /**
         * Capabilities
         * @description What this deployment can actually do, given its configuration.
         */
        Capabilities: {
            /** Attribution */
            attribution: components["schemas"]["AttributionEntry"][];
            /** Cesium Ion Token */
            cesium_ion_token?: string | null;
            /** Layers */
            layers: components["schemas"]["LayerCapability"][];
        };
        /**
         * EmergencyState
         * @description ADS-B emergency/priority status, as broadcast.
         *
         *     The squawk codes carry the same meaning by convention: 7500 hijack, 7600 radio
         *     failure, 7700 general emergency. Both are surfaced because an aircraft may set one
         *     without the other.
         * @enum {string}
         */
        EmergencyState: "none" | "general" | "lifeguard" | "minfuel" | "nordo" | "unlawful" | "downed" | "reserved";
        /**
         * FeedHealth
         * @description Whether one upstream feed is currently working.
         *
         *     Sent to clients so the UI can show a per-source degraded banner instead of silently
         *     displaying a frozen layer as if it were live. ``consecutive_failures`` is included
         *     because one failed poll is noise and five is an outage.
         */
        FeedHealth: {
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /** Entity Count */
            entity_count: number;
            /** Healthy */
            healthy: boolean;
            /** Last Error */
            last_error?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            layer: components["schemas"]["LayerName"];
            /** Poll Interval Seconds */
            poll_interval_seconds: number;
            /**
             * Rate Limited Until
             * @description Set when the upstream returned a throttling response. The UI says 'rate limited until X' rather than 'feed down', which is a materially different message: the data is fine, we are being asked to wait.
             */
            rate_limited_until?: string | null;
            /** Source */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness plus per-feed health.
         */
        Health: {
            /** Connected Clients */
            connected_clients: number;
            /** Feeds */
            feeds: components["schemas"]["FeedHealth"][];
            /** Status */
            status: string;
        };
        /**
         * LayerCapability
         * @description Whether one layer can run, and why not when it cannot.
         */
        LayerCapability: {
            /** Available */
            available: boolean;
            /** Layer */
            layer: string;
            /** Reason */
            reason?: string | null;
        };
        /** @enum {string} */
        LayerName: "aircraft" | "military" | "vessels" | "satellites" | "events" | "cameras";
        /**
         * LayerSummary
         * @description Counts and health per layer, for the layer rail and the degraded banners.
         */
        LayerSummary: {
            /** Feeds */
            feeds: components["schemas"]["FeedHealth"][];
            /** Layers */
            layers: {
                [key: string]: number;
            };
        };
        /**
         * Point
         * @description A position on the WGS84 ellipsoid.
         *
         *     ``altitude_m`` is metres above the ellipsoid, not above ground and not above mean sea
         *     level. It is ``None`` when the source does not report altitude, and ``0.0`` only when
         *     the source actively says the object is at the surface.
         */
        Point: {
            /** Altitude M */
            altitude_m?: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_aircraft_api_aircraft_get: {
        parameters: {
            query?: {
                west?: number | null;
                south?: number | null;
                east?: number | null;
                north?: number | null;
                military_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AircraftSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aircraft_api_aircraft__icao24__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                icao24: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    layer_summary_api_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerSummary"];
                };
            };
        };
    };
}
