/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/aircraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Aircraft
         * @description Aircraft currently known to the server.
         *
         *     Military aircraft are held in their own store because they come from a separate
         *     worldwide endpoint rather than the viewport query, and merging them into one store
         *     would let a global feed evict the local one every poll.
         */
        get: operations["list_aircraft_api_aircraft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aircraft/{icao24}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Aircraft
         * @description One aircraft by ICAO address, from either store. ``null`` when not currently seen.
         */
        get: operations["get_aircraft_api_aircraft__icao24__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Which layers this deployment can serve, and the attributions it must display.
         *
         *     The Cesium ion token is returned to the browser deliberately: it is a client-side
         *     token by design, scoped to the assets it can stream, unlike the feed keys which never
         *     leave the server.
         */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and upstream feed health.
         *
         *     Reports ``ok`` whenever the process is serving, even with every feed down, because
         *     this is a liveness probe rather than a data-quality judgement. Feed trouble is
         *     visible in ``feeds`` and is what the UI banners read.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer Summary
         * @description Entity counts per layer plus upstream health, for the layer rail.
         */
        get: operations["layer_summary_api_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/satellites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Satellites
         * @description Satellites currently held, one record per NORAD catalogue number.
         */
        get: operations["list_satellites_api_satellites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/satellites/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Satellite Elements
         * @description Cached orbital element sets, served without touching CelesTrak.
         *
         *     Declared before nothing else on this prefix by design: the store read above answers
         *     ``/api/satellites`` and this answers the element cache, which is what a client
         *     propagating orbits itself needs.
         */
        get: operations["satellite_elements_api_satellites_elements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Vessels
         * @description Vessels currently known to the server, merged across every reporting provider.
         *
         *     One record per MMSI whatever the provider count, per ADR 010, and each record names the
         *     provider whose report supplied it and how old that report was.
         */
        get: operations["list_vessels_api_vessels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vessels/{mmsi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vessel
         * @description One vessel by MMSI. ``null`` when not currently seen.
         */
        get: operations["get_vessel_api_vessels__mmsi__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aircraft
         * @description One aircraft as last reported by an ADS-B feed.
         *
         *     Immutable. The store replaces the whole object on each update rather than mutating,
         *     so a snapshot handed to the API or the WebSocket hub can never change underneath its
         *     reader.
         */
        Aircraft: {
            /** @default unknown */
            aircraft_class: components["schemas"]["AircraftClass"];
            /** Barometric Altitude M */
            barometric_altitude_m?: number | null;
            /**
             * Callsign
             * @description Flight identifier as broadcast, whitespace stripped.
             */
            callsign?: string | null;
            /**
             * Category
             * @description ADS-B emitter category, e.g. A3 for a large aeroplane.
             */
            category?: string | null;
            /** @default none */
            emergency: components["schemas"]["EmergencyState"];
            /** Geometric Altitude M */
            geometric_altitude_m?: number | null;
            /** Ground Speed Mps */
            ground_speed_mps?: number | null;
            /**
             * Icao24
             * @description 24-bit ICAO address, lowercase hex. The stable identity of the transponder.
             */
            icao24: string;
            /**
             * Is Military
             * @default false
             */
            is_military: boolean;
            /**
             * Kind
             * @default aircraft
             * @constant
             */
            kind: "aircraft";
            /**
             * Message Source
             * @description How the position was derived, verbatim from the feed: adsb_icao is a direct broadcast, mlat is multilaterated and less accurate, tisb_icao is rebroadcast ground data. Surfaced so the UI can be honest about accuracy.
             * @default unknown
             */
            message_source: string;
            /**
             * Messages Received
             * @default 0
             */
            messages_received: number;
            /**
             * Non Icao Address
             * @description The feed marked this address with a '~' prefix, meaning it is not a real ICAO allocation (typically a TIS-B ground vehicle or an ADS-R relay). The address is still a usable identity but should not be treated as an aircraft registration key.
             * @default false
             */
            non_icao_address: boolean;
            /**
             * Observed At
             * Format: date-time
             * @description When the feed generated the response carrying this record.
             */
            observed_at: string;
            /**
             * On Ground
             * @description True when the feed reported altitude as 'ground' rather than a number.
             * @default false
             */
            on_ground: boolean;
            /** Operator */
            operator?: string | null;
            /** Owner */
            owner?: string | null;
            point: components["schemas"]["Point"];
            /**
             * Position Age S
             * @description Seconds between the position fix and observed_at, as reported by the feed's seen_pos. Drives the stale badge in the UI.
             */
            position_age_s: number;
            /** Registered Country */
            registered_country?: string | null;
            /**
             * Registration
             * @description Tail number, from the feed's aircraft database rather than the air.
             */
            registration?: string | null;
            /**
             * Source
             * @description Which adapter produced this record, e.g. adsb.lol. Shown as attribution.
             */
            source: string;
            /** Squawk */
            squawk?: string | null;
            /**
             * Track Deg
             * @description True track over ground. Resolved from track, true_heading, mag_heading or dir, in that order of preference.
             */
            track_deg?: number | null;
            /**
             * Type Designator
             * @description ICAO type designator, e.g. B38M, GLF6, H60.
             */
            type_designator?: string | null;
            /**
             * Uses Privacy Address
             * @description Aircraft is broadcasting a privacy ICAO address. Not resolvable to an owner by design; we do not attempt to unmask it.
             * @default false
             */
            uses_privacy_address: boolean;
            /**
             * Vertical Rate Mps
             * @description Bounds are deliberately wider than any real aircraft. Live feeds emit glitch values (a -32,640 ft/min record appeared in the 2026-08-19 military sample); those must validate and be visible, not silently drop the aircraft.
             */
            vertical_rate_mps?: number | null;
        };
        /**
         * AircraftClass
         * @description How we classify an aircraft for display purposes.
         *
         *     Derived, not broadcast. ``MILITARY`` comes from the feed's own database flag;
         *     ``BUSINESS_JET`` from the type designator; ``ANONYMOUS`` marks an aircraft using a
         *     privacy ICAO address, which we display as anonymous by design and never attempt to
         *     resolve to an owner.
         * @enum {string}
         */
        AircraftClass: "unknown" | "commercial" | "business_jet" | "general_aviation" | "military" | "helicopter" | "anonymous";
        /**
         * AircraftSnapshot
         * @description Every aircraft currently held, optionally filtered to a viewport.
         */
        AircraftSnapshot: {
            /** Aircraft */
            aircraft: components["schemas"]["Aircraft"][];
            /** Count */
            count: number;
        };
        /**
         * AttributionEntry
         * @description One licence credit the UI is required to display.
         */
        AttributionEntry: {
            /** Licence */
            licence: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /** Url */
            url: string;
        };
        /**
         * Capabilities
         * @description What this deployment can actually do, given its configuration.
         */
        Capabilities: {
            /** Attribution */
            attribution: components["schemas"]["AttributionEntry"][];
            /** Cesium Ion Token */
            cesium_ion_token?: string | null;
            /** Layers */
            layers: components["schemas"]["LayerCapability"][];
        };
        /**
         * EmergencyState
         * @description ADS-B emergency/priority status, as broadcast.
         *
         *     The squawk codes carry the same meaning by convention: 7500 hijack, 7600 radio
         *     failure, 7700 general emergency. Both are surfaced because an aircraft may set one
         *     without the other.
         * @enum {string}
         */
        EmergencyState: "none" | "general" | "lifeguard" | "minfuel" | "nordo" | "unlawful" | "downed" | "reserved";
        /**
         * FeedHealth
         * @description Whether one upstream feed is currently working.
         *
         *     Sent to clients so the UI can show a per-source degraded banner instead of silently
         *     displaying a frozen layer as if it were live. ``consecutive_failures`` is included
         *     because one failed poll is noise and five is an outage.
         */
        FeedHealth: {
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /** Entity Count */
            entity_count: number;
            /** Healthy */
            healthy: boolean;
            /** Last Error */
            last_error?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            layer: components["schemas"]["LayerName"];
            /** Poll Interval Seconds */
            poll_interval_seconds: number;
            /**
             * Rate Limited Until
             * @description Set when the upstream returned a throttling response. The UI says 'rate limited until X' rather than 'feed down', which is a materially different message: the data is fine, we are being asked to wait.
             */
            rate_limited_until?: string | null;
            /** Source */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness plus per-feed health.
         */
        Health: {
            /** Connected Clients */
            connected_clients: number;
            /** Feeds */
            feeds: components["schemas"]["FeedHealth"][];
            /** Status */
            status: string;
        };
        /**
         * LayerCapability
         * @description Whether one layer can run, and why not when it cannot.
         *
         *     A merged layer also names its gated providers, as ``vessels/aishub`` and
         *     ``vessels/aisstream``. The layer itself stays available because its keyless providers
         *     carry it, and the entry for the gated provider says what is missing. Without that split
         *     a vessel layer serving Baltic ships would read as entirely off.
         */
        LayerCapability: {
            /** Available */
            available: boolean;
            /** Layer */
            layer: string;
            /** Reason */
            reason?: string | null;
        };
        /** @enum {string} */
        LayerName: "aircraft" | "military" | "vessels" | "satellites" | "events" | "cameras";
        /**
         * LayerSummary
         * @description Counts and health per layer, for the layer rail and the degraded banners.
         */
        LayerSummary: {
            /** Feeds */
            feeds: components["schemas"]["FeedHealth"][];
            /** Layers */
            layers: {
                [key: string]: number;
            };
            /**
             * Providers
             * @default []
             */
            providers: components["schemas"]["ProviderCoverage"][];
        };
        /**
         * NavigationalStatus
         * @description AIS navigational status, as broadcast, per ITU-R M.1371.
         *
         *     What the master set on the transponder, so it disagrees with the vessel's actual
         *     behaviour often enough that the card shows both this and the speed.
         * @enum {string}
         */
        NavigationalStatus: "under_way_using_engine" | "at_anchor" | "not_under_command" | "restricted_manoeuvrability" | "constrained_by_draught" | "moored" | "aground" | "engaged_in_fishing" | "under_way_sailing" | "towing_astern" | "pushing_ahead" | "ais_sart_active";
        /**
         * Point
         * @description A position on the WGS84 ellipsoid.
         *
         *     ``altitude_m`` is metres above the ellipsoid, not above ground and not above mean sea
         *     level. It is ``None`` when the source does not report altitude, and ``0.0`` only when
         *     the source actively says the object is at the surface.
         */
        Point: {
            /** Altitude M */
            altitude_m?: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * ProviderCoverage
         * @description One provider's contribution to a merged layer, for the last cycle.
         *
         *     ADR 010 asks for two things this carries. ``exclusive`` is the provider-attributable
         *     count, so "ships only this network can see" is measured rather than asserted. ``error``
         *     names a provider that dropped out, which is how the layer reports itself degraded
         *     instead of quietly covering less.
         *
         *     This is coverage, not corroboration, and the two must not be confused: under R1 in
         *     ``docs/pending-decisions.md`` three providers reporting one ship are still one origin,
         *     because they are repeating one AIS broadcast. Nothing here may be counted as
         *     independent sources.
         */
        ProviderCoverage: {
            /** Error */
            error?: string | null;
            /** Exclusive */
            exclusive: number;
            /** Layer */
            layer: string;
            /** Provider */
            provider: string;
            /** Records */
            records: number;
        };
        /**
         * Satellite
         * @description One GP element set, keyed on the NORAD catalogue number.
         *
         *     Immutable, like every entity here. Field names are ours; the mapping from the OMM
         *     keyword to each one is in the adapter and only there.
         */
        Satellite: {
            /**
             * Arg Of Pericenter Deg
             * @description Degrees.
             */
            arg_of_pericenter_deg: number;
            /**
             * Bstar
             * @description B* drag term, inverse earth radii. Zero on the recorded TDRS 3 record, which is a real value for a geostationary object and not a missing one.
             */
            bstar: number;
            /**
             * Classification Type
             * @description U unclassified, C classified, S secret. Both sampled records read U.
             */
            classification_type: string;
            /**
             * Eccentricity
             * @description Dimensionless. Outside 0 to 1 is SatRecError 1, an element set SGP4 cannot propagate, so it is refused here.
             */
            eccentricity: number;
            /**
             * Element Set No
             * @description Element set number. Both recorded records read 999.
             */
            element_set_no: number;
            /**
             * Ephemeris Type
             * @description Always 0 on CelesTrak GP data, which means SGP4. Carried because it is part of the element set the propagator is handed.
             */
            ephemeris_type: number;
            /**
             * Epoch
             * Format: date-time
             * @description The instant these elements describe, UTC, serialised with a Z suffix.
             */
            epoch: string;
            /**
             * Fetched At
             * Format: date-time
             * @description When we fetched this element set. Distinct from epoch, which is when the elements were fitted: the fetch says how current our copy is, the epoch says how current the orbit determination is, and only the second one decides whether a propagated position is worth drawing.
             */
            fetched_at: string;
            /**
             * Group
             * @description The CelesTrak group this element set was fetched from, e.g. stations. Provenance, and the reason two overlapping groups cannot double-count an object: the store is keyed on the catalogue number, not on the group.
             */
            group: string;
            /**
             * Inclination Deg
             * @description Degrees.
             */
            inclination_deg: number;
            /**
             * Kind
             * @default satellite
             * @constant
             */
            kind: "satellite";
            /**
             * Mean Anomaly Deg
             * @description Degrees.
             */
            mean_anomaly_deg: number;
            /**
             * Mean Motion
             * @description Revolutions per day, no conversion from the wire. At or below zero is SatRecError 2 and cannot be propagated, so it is refused rather than stored.
             */
            mean_motion: number;
            /**
             * Mean Motion Ddot
             * @description Second derivative, already sixthed by the provider. Zero on both recorded records.
             */
            mean_motion_ddot: number;
            /**
             * Mean Motion Dot
             * @description First derivative of mean motion, already halved by the provider. Negative on the recorded TDRS 3 record. Goes to satellite.js verbatim.
             */
            mean_motion_dot: number;
            /**
             * Norad Cat Id
             * @description NORAD catalogue number, the identity of the object. 1 to 9 digits, never zero-padded to a fixed width.
             */
            norad_cat_id: number;
            /**
             * Object Id
             * @description International designator, e.g. 1998-067A. Also absent for analyst objects.
             */
            object_id?: string | null;
            /**
             * Object Name
             * @description Name as published, e.g. 'ISS (ZARYA)'. Absent for analyst objects in the 80000 series, which carry no name at all.
             */
            object_name?: string | null;
            /**
             * Ra Of Asc Node Deg
             * @description Right ascension of the ascending node, degrees. Not a compass bearing, so it is bounded explicitly rather than typed as one.
             */
            ra_of_asc_node_deg: number;
            /**
             * Rev At Epoch
             * @description Revolution number at epoch. 58157 on the recorded ISS record, so the 5-digit TLE column is already at its limit here too.
             */
            rev_at_epoch: number;
            /**
             * Source
             * @description Which adapter produced this record, e.g. celestrak. Shown as attribution.
             */
            source: string;
        };
        /**
         * SatelliteElements
         * @description Cached OMM element sets, with when each group was last fetched.
         *
         *     ``fetched`` is the evidence for the two-hour floor: it is the instant of the fetch,
         *     which is a different thing from an element set's epoch. One record per catalogue number,
         *     freshest epoch winning, because CelesTrak groups overlap.
         */
        SatelliteElements: {
            /** Count */
            count: number;
            /** Fetched */
            fetched: {
                [key: string]: string;
            };
            /** Satellites */
            satellites: components["schemas"]["Satellite"][];
        };
        /**
         * SatelliteSnapshot
         * @description Every satellite currently held.
         *
         *     No bounding box, and there is nothing to filter on: a satellite record carries orbital
         *     elements rather than a position, and the browser propagates it. Filtering here would
         *     mean running SGP4 on the server for every object on every request.
         */
        SatelliteSnapshot: {
            /** Count */
            count: number;
            /** Satellites */
            satellites: components["schemas"]["Satellite"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Vessel
         * @description One vessel as last reported by an AIS feed.
         *
         *     Immutable, like every entity here: the store replaces the whole object on update, so a
         *     snapshot handed to the API or the WebSocket hub cannot change underneath its reader.
         *
         *     ``point.altitude_m`` is always ``None``. AIS reports no altitude, and 0.0 would be this
         *     contract asserting the source said "at the surface" when it said nothing at all.
         */
        Vessel: {
            /**
             * Beam M
             * @description Overall beam, summed in the adapter from reference points C and D.
             */
            beam_m?: number | null;
            /**
             * Call Sign
             * @description Radio call sign. The feed sends an empty string when it has none, which the adapter maps to None.
             */
            call_sign?: string | null;
            /**
             * Course Over Ground Deg
             * @description Course over ground, the direction the vessel is actually moving. 0.0 is a real course due north; 360.0 on the wire means not available and is mapped to None before this bound is applied.
             */
            course_over_ground_deg?: number | null;
            /**
             * Destination
             * @description Destination as typed by the crew, free text and often a route like FIHEL<>FIMHQ<>SESTO. Empty on 91 of 950 live records, mapped to None.
             */
            destination?: string | null;
            /**
             * Draught M
             * @description Maximum present static draught in metres. Decimetres on the AIS endpoint and metres on the port-call endpoint, so the conversion is per endpoint in the adapter. 0 means not available.
             */
            draught_m?: number | null;
            /** @description Estimated time of arrival, decoded from the packed AIS field. Carries no year, because the wire field has none. */
            eta?: components["schemas"]["VesselEta"] | null;
            /**
             * Imo
             * @description IMO ship identification number, seven digits. 0 means not available on the wire and so does anything outside the seven-digit range: the live feed carried values up to 912974400, which is not an IMO number. Both map to None in the adapter, because dropping a real ship over one junk optional field would be worse than not knowing its IMO.
             */
            imo?: number | null;
            /**
             * Kind
             * @default vessel
             * @constant
             */
            kind: "vessel";
            /**
             * Length M
             * @description Overall length, summed in the adapter from the AIS reference points A and B. The bound is what those two 9-bit fields can hold, not what a real ship is, so a junk dimension does not drop a real vessel.
             */
            length_m?: number | null;
            /**
             * Mmsi
             * @description Maritime Mobile Service Identity, nine digits, zero-padded. The vessel merge key under ADR 010, and only ever a ship-station MMSI: the first three digits are the ITU MID, which gives the flag state in phase 5 with no registry call.
             */
            mmsi: string;
            /**
             * Name
             * @description Vessel name as broadcast, capped at 20 characters upstream. None when no static record joined to the position, which was 108 of 1,058 on 2026-08-19.
             */
            name?: string | null;
            /** @description What the master set on the transponder. None for the undefined code and the reserved ones. */
            navigational_status?: components["schemas"]["NavigationalStatus"] | null;
            /**
             * Observed At
             * Format: date-time
             * @description When the provider generated the response carrying this record.
             */
            observed_at: string;
            point: components["schemas"]["Point"];
            /**
             * Position Age S
             * @description Seconds between the position fix and observed_at. Per ADR 010 every record carries how old its report is, because recency is what resolves a conflict between two providers and the card has to be able to show why. Digitraffic's default query window is 24 hours, so an age of tens of thousands of seconds is a real answer and not a fault.
             */
            position_age_s: number;
            /**
             * Rate Of Turn Deg Per Min
             * @description Rate of turn, decoded from the signed ROT_AIS wire value where ROT_AIS is 4.733 times the square root of the rate. Negative is to port. None when the feed said not available (-128) and also at +/-127, where the feed says the vessel is turning faster than 5 degrees per 30 seconds without giving a rate.
             */
            rate_of_turn_deg_per_min?: number | null;
            /**
             * Ship Type
             * @description AIS ship and cargo type code, 1 to 99. 0 means not available.
             */
            ship_type?: number | null;
            /**
             * Source
             * @description Which provider supplied this record, e.g. digitraffic. Per ADR 010 this is per record and never per layer: a merged store that cannot say which network saw a given ship is unauditable. The full list of providers that saw it rides on the merge result in services/union.py, and under R1 in docs/pending-decisions.md that list is still one origin for corroboration.
             */
            source: string;
            /**
             * Speed Over Ground Mps
             * @description Speed over ground, converted from knots in the adapter.
             */
            speed_over_ground_mps?: number | null;
            /**
             * True Heading Deg
             * @description Where the bow points, which is not the course over ground: a vessel in a tideway carries a heading well off its track. 511 means not available.
             */
            true_heading_deg?: number | null;
        };
        /**
         * VesselEta
         * @description A decoded AIS estimated time of arrival.
         *
         *     **Not a datetime, and it must never be turned into one.** The wire field is a 20-bit
         *     packed integer holding month, day, hour and minute, and it carries no year at all, so
         *     any year is a guess. Storing the raw integer as though it were an epoch dates every
         *     vessel to 1970.
         */
        VesselEta: {
            /** Day */
            day: number;
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
            /** Month */
            month: number;
        };
        /**
         * VesselSnapshot
         * @description Every vessel currently held, optionally filtered to a viewport.
         */
        VesselSnapshot: {
            /** Count */
            count: number;
            /** Vessels */
            vessels: components["schemas"]["Vessel"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_aircraft_api_aircraft_get: {
        parameters: {
            query?: {
                west?: number | null;
                south?: number | null;
                east?: number | null;
                north?: number | null;
                military_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AircraftSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aircraft_api_aircraft__icao24__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                icao24: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    layer_summary_api_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerSummary"];
                };
            };
        };
    };
    list_satellites_api_satellites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatelliteSnapshot"];
                };
            };
        };
    };
    satellite_elements_api_satellites_elements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatelliteElements"];
                };
            };
        };
    };
    list_vessels_api_vessels_get: {
        parameters: {
            query?: {
                west?: number | null;
                south?: number | null;
                east?: number | null;
                north?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vessel_api_vessels__mmsi__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mmsi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
