// CC0 Wikidata snapshot; generated by scripts/build-discovery-pack.mjs.
export const starterPack = {
  format: 'gods-eye-view/discovery-pack',
  version: 1,
  title: 'Discovery starter: Earth, Moon and Mars',
  license: 'CC0-1.0',
  selection:
    'A small editorial sample of nine Earth places, two aircraft families and four Moon/Mars sites. Not a global ranking or complete atlas.',
  cards: [
    {
      id: 'Q243',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Eiffel Tower',
        fr: 'tour Eiffel',
      },
      descriptions: {
        en: 'tower located on the Champ de Mars in Paris, France',
        fr: 'tour de fer puddlé de 330 mètres à Paris, France',
      },
      coordinate: {
        lat: 48.858296,
        lon: 2.294479,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.000002777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Eiffel_Tower',
        fr: 'https://fr.wikipedia.org/wiki/Tour_Eiffel',
      },
      officialSite: 'https://www.toureiffel.paris/',
      aliases: ['Eiffel', 'Tour Eiffel'],
      facts: [
        {
          property: 'P571',
          label: 'Inception / Création',
          value: '1887-01-28',
        },
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '330 m',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q243',
        revision: 2545452862,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q10285',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Colosseum',
        fr: 'Colisée',
      },
      descriptions: {
        en: 'ancient Roman amphitheatre, a landmark of Rome, Italy',
        fr: 'monument de la ville de Rome',
      },
      coordinate: {
        lat: 41.890277777778,
        lon: 12.492222222222,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.000277778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Colosseum',
        fr: 'https://fr.wikipedia.org/wiki/Colis%C3%A9e',
      },
      officialSite: 'https://colosseo.it/area/colosseo/',
      aliases: ['Colosseum', 'Colisée'],
      facts: [
        {
          property: 'P571',
          label: 'Inception / Création',
          value: '82',
        },
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '48 m',
        },
        {
          property: 'P2046',
          label: 'Area / Surface',
          value: '5000 m²',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q10285',
        revision: 2551136894,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q9141',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Taj Mahal',
        fr: 'Taj Mahal',
      },
      descriptions: {
        en: 'marble mausoleum in Agra, India',
        fr: "mausolée de marbre à Agra, État de l'Uttar Pradesh, Inde",
      },
      coordinate: {
        lat: 27.175,
        lon: 78.04194444444444,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.0002777777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Taj_Mahal',
        fr: 'https://fr.wikipedia.org/wiki/Taj_Mahal',
      },
      officialSite: 'https://www.tajmahal.gov.in/',
      aliases: ['Taj Mahal'],
      facts: [
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '73 m',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q9141',
        revision: 2548165205,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q39671',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Stonehenge',
        fr: 'Stonehenge',
      },
      descriptions: {
        en: 'Neolithic henge monument in Amesbury, Wiltshire, England, UK',
        fr: 'monument préhistorique dans le Wiltshire, Angleterre',
      },
      coordinate: {
        lat: 51.17888888888889,
        lon: -1.826111111111111,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.00000277778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Stonehenge',
        fr: 'https://fr.wikipedia.org/wiki/Stonehenge',
      },
      officialSite: 'https://www.english-heritage.org.uk/stonehenge',
      aliases: ['Stonehenge'],
      facts: [],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q39671',
        revision: 2549781117,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q37200',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Great Pyramid of Giza',
        fr: 'pyramide de Khéops',
      },
      descriptions: {
        en: 'oldest and largest of the three pyramids in the Giza Necropolis; one of the seven ancient wonders of the world',
        fr: 'plus ancienne et plus grande des trois pyramides de la nécropole de Gizeh',
      },
      coordinate: {
        lat: 29.97915,
        lon: 31.13422,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.00001,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza',
        fr: 'https://fr.wikipedia.org/wiki/Pyramide_de_Kh%C3%A9ops',
      },
      officialSite: null,
      aliases: ['Great Pyramid', 'Pyramide de Khéops'],
      facts: [
        {
          property: 'P571',
          label: 'Inception / Création',
          value: '-2560',
        },
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '137.5 m',
        },
        {
          property: 'P2046',
          label: 'Area / Surface',
          value: '53061.12 m²',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q37200',
        revision: 2549169562,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q676203',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Machu Picchu',
        fr: 'Machu Picchu',
      },
      descriptions: {
        en: '15th-century Inca citadel in the Peruvian Andes and UNESCO World Heritage Site',
        fr: 'ancienne cité inca du XVe siècle au Pérou',
      },
      coordinate: {
        lat: -13.163333333333334,
        lon: -72.54555555555555,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.0002777777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Machu_Picchu',
        fr: 'https://fr.wikipedia.org/wiki/Machu_Picchu',
      },
      officialSite: null,
      aliases: ['Machu Picchu'],
      facts: [
        {
          property: 'P571',
          label: 'Inception / Création',
          value: '1450',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q676203',
        revision: 2551468667,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q118841',
      kind: 'landform',
      body: 'earth',
      labels: {
        en: 'Grand Canyon',
        fr: 'Grand Canyon',
      },
      descriptions: {
        en: 'steep-sided canyon carved by the Colorado River in Arizona, United States',
        fr: "canyon de l'Ouest des États-Unis",
      },
      coordinate: {
        lat: 36.0975,
        lon: -112.09527777777778,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.0002777777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Grand_Canyon',
        fr: 'https://fr.wikipedia.org/wiki/Grand_Canyon',
      },
      officialSite: null,
      aliases: ['Grand Canyon'],
      facts: [],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q118841',
        revision: 2553303920,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q5788',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Petra',
        fr: 'Pétra',
      },
      descriptions: {
        en: 'ancient rock-cut historical city in Jordan',
        fr: "ancienne cité nabatéenne située au sud de l'actuelle Jordanie",
      },
      coordinate: {
        lat: 30.328888888889,
        lon: 35.440277777778,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 0.00027777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Petra',
        fr: 'https://fr.wikipedia.org/wiki/P%C3%A9tra',
      },
      officialSite: null,
      aliases: ['Petra', 'Pétra'],
      facts: [
        {
          property: 'P571',
          label: 'Inception / Création',
          value: '-800',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q5788',
        revision: 2532483446,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q9202',
      kind: 'landmark',
      body: 'earth',
      labels: {
        en: 'Statue of Liberty',
        fr: 'statue de la Liberté',
      },
      descriptions: {
        en: 'monument in New York',
        fr: 'monument de la ville de New York',
      },
      coordinate: {
        lat: 40.689209166667,
        lon: -74.044425277778,
        globe: 'http://www.wikidata.org/entity/Q2',
        precision: 2.7777777777778e-7,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Statue_of_Liberty',
        fr: 'https://fr.wikipedia.org/wiki/Statue_de_la_Libert%C3%A9',
      },
      officialSite: null,
      aliases: ['Statue of Liberty', 'Statue de la Liberté'],
      facts: [
        {
          property: 'P571',
          label: 'Inception / Création',
          value: '1886',
        },
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '46 m',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q9202',
        revision: 2549717859,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q6475',
      kind: 'vehicle-type',
      body: 'earth',
      labels: {
        en: 'Airbus A320 family',
        fr: 'Airbus A320',
      },
      descriptions: {
        en: '1987 jet airliner family by Airbus including the A318, A319, A320, A321 and ACJ series',
        fr: "famille d'avions produits par Airbus",
      },
      coordinate: null,
      articles: {
        en: 'https://en.wikipedia.org/wiki/Airbus_A320_family',
        fr: 'https://fr.wikipedia.org/wiki/Airbus_A320',
      },
      officialSite:
        'https://www.airbus.com/aircraft/passenger-aircraft/a320-family.html',
      aliases: ['A320', 'A319', 'A318', 'A321', 'A20N', 'A21N'],
      facts: [
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '12.56 m',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q6475',
        revision: 2517805369,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Vehicle family/type, not identification of an observed vehicle.',
    },
    {
      id: 'Q6387',
      kind: 'vehicle-type',
      body: 'earth',
      labels: {
        en: 'Boeing 737',
        fr: 'Boeing 737',
      },
      descriptions: {
        en: '1967 twin-engine jet-powered airliner family',
        fr: 'avions de ligne monocouloirs',
      },
      coordinate: null,
      articles: {
        en: 'https://en.wikipedia.org/wiki/Boeing_737',
        fr: 'https://fr.wikipedia.org/wiki/Boeing_737',
      },
      officialSite: null,
      aliases: ['B737', 'B738', 'B739', 'B38M', 'B39M', 'Boeing 737'],
      facts: [
        {
          property: 'P2048',
          label: 'Height / Hauteur',
          value: '12.50 m',
        },
      ],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q6387',
        revision: 2544870582,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Vehicle family/type, not identification of an observed vehicle.',
    },
    {
      id: 'Q520',
      kind: 'planetary-feature',
      body: 'mars',
      labels: {
        en: 'Olympus Mons',
        fr: 'Olympus Mons',
      },
      descriptions: {
        en: 'tallest volcano on Mars',
        fr: 'volcan de la planète Mars',
      },
      coordinate: {
        lat: 18.65,
        lon: 226.2,
        globe: 'http://www.wikidata.org/entity/Q111',
        precision: 0.0002777777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Olympus_Mons',
        fr: 'https://fr.wikipedia.org/wiki/Olympus_Mons',
      },
      officialSite: null,
      aliases: ['Olympus Mons'],
      facts: [],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q520',
        revision: 2550387158,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q621110',
      kind: 'planetary-feature',
      body: 'mars',
      labels: {
        en: 'Valles Marineris',
        fr: 'Valles Marineris',
      },
      descriptions: {
        en: 'vallis on Mars',
        fr: 'vallis sur Mars',
      },
      coordinate: {
        lat: -14.01,
        lon: 301.41,
        globe: 'http://www.wikidata.org/entity/Q111',
        precision: 0.01,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Valles_Marineris',
        fr: 'https://fr.wikipedia.org/wiki/Valles_Marineris',
      },
      officialSite: null,
      aliases: ['Valles Marineris'],
      facts: [],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q621110',
        revision: 2516708244,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q631696',
      kind: 'planetary-feature',
      body: 'moon',
      labels: {
        en: 'Tycho',
        fr: 'Tycho',
      },
      descriptions: {
        en: 'lunar crater',
        fr: 'cratère lunaire',
      },
      coordinate: {
        lat: -43.3,
        lon: -11.22,
        globe: 'http://www.wikidata.org/entity/Q405',
        precision: 0.01,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Tycho_(lunar_crater)',
        fr: 'https://fr.wikipedia.org/wiki/Tycho_(crat%C3%A8re)',
      },
      officialSite: null,
      aliases: ['Tycho crater', 'Cratère Tycho'],
      facts: [],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q631696',
        revision: 2548488901,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
    {
      id: 'Q732758',
      kind: 'mission-site',
      body: 'moon',
      labels: {
        en: 'Statio Tranquillitatis',
        fr: 'Statio Tranquillitatis',
      },
      descriptions: {
        en: 'Apollo 11 landing site',
        fr: "site d'atterrissage d'Apollo 11",
      },
      coordinate: {
        lat: 0.6875,
        lon: 23.433333333333334,
        globe: 'http://www.wikidata.org/entity/Q405',
        precision: 0.0002777777777777778,
      },
      articles: {
        en: 'https://en.wikipedia.org/wiki/Tranquility_Base',
        fr: 'https://fr.wikipedia.org/wiki/Base_de_la_Tranquillit%C3%A9',
      },
      officialSite: null,
      aliases: ['Tranquility Base', 'Base de la Tranquillité'],
      facts: [],
      provenance: {
        source: 'Wikidata',
        sourceUrl: 'https://www.wikidata.org/wiki/Q732758',
        revision: 2453864509,
        retrievedAt: '2026-10-05',
        license: 'CC0-1.0',
      },
      association:
        'Entity selected by its source ID, not inferred from imagery.',
    },
  ],
};
