#!/usr/bin/env python3
"""Build the World Desk 5000-year event catalog (3000 BCE–present)."""
import json
from pathlib import Path

# year, year_end, category, title, place, lat, lon, summary, traditional
# year < 0 is BCE. Coordinates are approximate. Traditional/legendary dates are flagged.
RAW = [
    (-3000, None, "empire", "Uruk at its early peak", "Uruk, Mesopotamia", 31.32, 45.64, "One of the first true cities, in Sumer. Writing and monumental temples take shape."),
    (-2686, -2181, "empire", "Old Kingdom of Egypt", "Memphis, Egypt", 29.85, 31.26, "Pyramid Age. Divine kingship and a unified Nile state."),
    (-2560, None, "empire", "Great Pyramid of Giza completed", "Giza, Egypt", 29.98, 31.13, "Khufu's tomb — still the emblem of Old Kingdom power."),
    (-2500, None, "empire", "Indus cities at Mohenjo-daro and Harappa", "Mohenjo-daro", 27.32, 68.14, "Planned brick cities, drains, and a still-undeciphered script."),
    (-2334, -2279, "empire", "Sargon of Akkad", "Akkad, Mesopotamia", 33.09, 44.10, "Often called the first empire-builder of the Near East."),
    (-2200, -2100, "calamity", "4.2-kiloyear drought", "Near East / North Africa", 30.0, 40.0, "A centuries-long dry spell implicated in the collapse of Akkad and Old Kingdom Egypt."),
    (-2112, -2004, "empire", "Third Dynasty of Ur", "Ur, Mesopotamia", 30.96, 46.10, "Sumerian revival, law, and the ziggurat of Ur."),
    (-1894, -1595, "empire", "Old Babylonian period", "Babylon", 32.54, 44.42, "Hammurabi's Babylon dominates southern Mesopotamia."),
    (-1810, None, "prophet", "Abraham (traditional lifetime)", "Canaan / Mesopotamia", 31.77, 35.22, "Patriarch in Jewish, Christian, and Islamic tradition. Date is traditional, not archaeological.", True),
    (-1792, -1750, "politics", "Code of Hammurabi", "Babylon", 32.54, 44.42, "One of the earliest surviving law collections, carved in stone."),
    (-1700, None, "calamity", "Santorini (Thera) eruption, approximate", "Santorini, Greece", 36.40, 25.40, "A colossal Bronze Age eruption; often linked to disruptions in the Aegean.", True),
    (-1650, -1550, "empire", "Hyksos in the Nile Delta", "Avaris, Egypt", 30.79, 31.82, "West Asian rulers in Egypt; later expelled as the New Kingdom begins."),
    (-1600, -1046, "empire", "Shang dynasty", "Anyang, China", 36.10, 114.39, "Oracle bones, bronze, and the first fully historical Chinese dynasty."),
    (-1550, -1077, "empire", "Egyptian New Kingdom", "Thebes, Egypt", 25.72, 32.61, "Empire on the Nile: Hatshepsut, Akhenaten, Tutankhamun, Ramesses II."),
    (-1279, -1213, "politics", "Ramesses II", "Pi-Ramesses, Egypt", 30.80, 31.83, "Long-reigning pharaoh of temples, Qadesh, and later legend."),
    (-1274, None, "war", "Battle of Qadesh", "Qadesh, Syria", 34.55, 36.51, "Ramesses II vs. the Hittites — among the earliest battles with detailed records."),
    (-1250, None, "prophet", "Moses and the Exodus (traditional)", "Sinai / Egypt", 28.54, 33.97, "Foundational story of Israelite origins. Historicity and date remain debated.", True),
    (-1200, -1150, "calamity", "Late Bronze Age collapse", "Eastern Mediterranean", 35.0, 33.0, "Palaces fall from Greece to the Levant. Drought, migration, and war are all suspects."),
    (-1200, None, "war", "Trojan War (legendary)", "Troy, Anatolia", 39.96, 26.24, "Homeric war. A real city burned; the epic is literature, not a dispatch.", True),
    (-1046, -256, "empire", "Zhou dynasty", "Luoyang, China", 34.62, 112.45, "Mandate of Heaven, feudal order, and the classical Chinese philosophical age."),
    (-1000, None, "prophet", "Zoroaster (approximate)", "Eastern Iran", 36.26, 59.62, "Founder of Zoroastrianism. Dates range widely in the sources.", True),
    (-969, -930, "politics", "Solomon's temple (traditional)", "Jerusalem", 31.78, 35.24, "First Temple in Israelite tradition.", True),
    (-900, -800, "culture", "Iliad and Odyssey take written form", "Ionia / Greece", 38.32, 26.30, "Homeric epics, foundational for Greek identity."),
    (-814, None, "empire", "Carthage founded (traditional)", "Carthage, Tunisia", 36.85, 10.32, "Phoenician colony that becomes Rome's great rival.", True),
    (-776, None, "culture", "First recorded Olympic Games", "Olympia, Greece", 37.64, 21.63, "Pan-Hellenic games; later used as a dating system."),
    (-753, None, "empire", "Founding of Rome (traditional)", "Rome", 41.89, 12.48, "Romulus in legend; archaeology shows villages on the Palatine.", True),
    (-722, None, "war", "Assyria destroys the Kingdom of Israel", "Samaria", 32.28, 35.20, "Ten tribes lost to empire; Judah survives in the south."),
    (-700, None, "prophet", "Isaiah active in Judah", "Jerusalem", 31.78, 35.24, "Prophet of warning and consolation during Assyrian pressure."),
    (-612, None, "war", "Fall of Nineveh", "Nineveh, Iraq", 36.36, 43.15, "Assyrian capital falls to Babylonians and Medes."),
    (-586, None, "war", "Babylon destroys Jerusalem and the First Temple", "Jerusalem", 31.78, 35.24, "Judah's elite deported. A wound that shapes Jewish memory."),
    (-563, -483, "prophet", "Siddhartha Gautama (the Buddha)", "Lumbini / Magadha", 27.47, 83.28, "Teaching of the Middle Way. Dates vary by tradition."),
    (-551, -479, "prophet", "Confucius", "Qufu, China", 35.60, 116.98, "Ethics, ritual, and government as moral craft."),
    (-550, None, "prophet", "Laozi (traditional)", "Zhou China", 34.27, 108.95, "Dao De Jing attributed to him. Historicity is uncertain.", True),
    (-539, None, "empire", "Cyrus takes Babylon", "Babylon", 32.54, 44.42, "Persian Empire absorbs Mesopotamia; some exiles return to Judah."),
    (-525, None, "war", "Persia conquers Egypt", "Pelusium, Egypt", 31.04, 32.55, "Cambyses II ends native pharaonic independence for a time."),
    (-509, None, "politics", "Roman Republic founded (traditional)", "Rome", 41.89, 12.48, "Kings expelled; consuls and Senate in later Roman telling.", True),
    (-508, None, "politics", "Cleisthenes' reforms in Athens", "Athens", 37.97, 23.72, "Foundations of Athenian democracy."),
    (-490, None, "war", "Battle of Marathon", "Marathon, Greece", 38.15, 23.95, "Athens checks the first Persian landing in Attica."),
    (-480, None, "war", "Thermopylae and Salamis", "Thermopylae / Salamis", 38.80, 22.54, "Spartan stand; then a Greek naval victory that saves the mainland."),
    (-431, -404, "war", "Peloponnesian War", "Athens / Sparta", 37.97, 23.72, "Athens vs. Sparta wrecks the classical Greek order."),
    (-430, -426, "calamity", "Plague of Athens", "Athens", 37.97, 23.72, "Typhoid-like outbreak during the Spartan siege. Thucydides survived it."),
    (-336, -323, "empire", "Alexander the Great", "Pella / Babylon", 40.76, 22.52, "Macedon overruns Persia; Hellenistic world from Greece to the Indus."),
    (-323, None, "death", "Death of Alexander in Babylon", "Babylon", 32.54, 44.42, "At 32. His generals carve up the empire."),
    (-264, -146, "war", "Punic Wars", "Carthage / Rome", 36.85, 10.32, "Rome destroys Carthage and becomes a Mediterranean superpower."),
    (-221, None, "empire", "Qin unifies China", "Xianyang, China", 34.32, 108.72, "First emperor, roads, script, and the first Great Wall works."),
    (-218, -201, "war", "Hannibal crosses the Alps", "Alps / Cannae", 45.05, 6.63, "Carthage's war in Italy; Rome still wins the long war."),
    (-206, 220, "empire", "Han dynasty", "Chang'an, China", 34.27, 108.95, "Civil service, Silk Road, and a Chinese imperial template."),
    (-146, None, "war", "Rome razes Carthage and Corinth", "Carthage", 36.85, 10.32, "Two ancient cities erased in a single year of Roman will."),
    (-73, -71, "war", "Spartacus revolt", "Capua / southern Italy", 41.13, 14.25, "Gladiators and slaves against Rome; crushed by Crassus."),
    (-49, -45, "war", "Caesar's civil war", "Rubicon / Rome", 44.10, 12.40, "The Republic's last generation fights itself."),
    (-44, None, "death", "Assassination of Julius Caesar", "Rome", 41.89, 12.48, "Ides of March. The Republic does not recover."),
    (-31, None, "war", "Battle of Actium", "Actium, Greece", 38.92, 20.77, "Octavian defeats Antony and Cleopatra; the Empire begins."),
    (-30, None, "death", "Deaths of Antony and Cleopatra", "Alexandria, Egypt", 31.20, 29.92, "Ptolemaic Egypt becomes a Roman province."),
    (-27, None, "empire", "Augustus and the Roman Empire", "Rome", 41.89, 12.48, "Principate: republic in costume, monarchy in fact."),
    (-4, 30, "prophet", "Jesus of Nazareth (traditional dates)", "Nazareth / Jerusalem", 32.70, 35.30, "Central figure of Christianity. Birth year is estimated; crucifixion c. 30–33 CE.", True),
    (14, None, "death", "Death of Augustus", "Nola, Italy", 40.93, 14.53, "The imperial system outlives its inventor."),
    (64, None, "calamity", "Great Fire of Rome", "Rome", 41.89, 12.48, "Nero's Rome burns; Christians are later scapegoated."),
    (70, None, "war", "Romans destroy the Second Temple", "Jerusalem", 31.78, 35.24, "Titus takes the city. Judaism reorganizes without the Temple."),
    (79, None, "calamity", "Vesuvius buries Pompeii and Herculaneum", "Pompeii, Italy", 40.75, 14.49, "Pliny the Younger watches from the bay. The towns freeze in ash."),
    (135, None, "war", "Bar Kokhba revolt crushed", "Judea", 31.78, 35.24, "Hadrian bans Jews from Jerusalem; the province is renamed."),
    (165, 180, "calamity", "Antonine Plague", "Roman Empire", 41.89, 12.48, "Probably smallpox. Marcus Aurelius's wars and cities both suffer."),
    (224, 651, "empire", "Sasanian Empire", "Ctesiphon, Iraq", 33.09, 44.58, "Rome/Byzantium's equal in the east until the Arab conquests."),
    (313, None, "politics", "Edict of Milan", "Milan", 45.46, 9.19, "Constantine and Licinius legalize Christianity."),
    (330, None, "empire", "Constantinople founded as imperial capital", "Constantinople", 41.01, 28.98, "New Rome on the Bosporus."),
    (395, None, "empire", "Permanent split of the Roman Empire", "Rome / Constantinople", 41.01, 28.98, "West and East go their own ways."),
    (410, None, "war", "Visigoths sack Rome", "Rome", 41.89, 12.48, "Alaric. A psychological rupture more than the city's last day."),
    (451, None, "war", "Battle of the Catalaunian Plains", "Champagne, France", 49.0, 4.4, "Aetius and allies halt Attila in Gaul."),
    (476, None, "empire", "End of the Western Roman Empire", "Ravenna, Italy", 44.42, 12.20, "Odovacer deposes Romulus Augustulus. The East continues."),
    (541, 549, "calamity", "Plague of Justinian", "Constantinople / Mediterranean", 41.01, 28.98, "Yersinia pestis. First recorded pandemic of bubonic plague."),
    (570, 632, "prophet", "Muhammad", "Mecca / Medina", 21.42, 39.83, "Prophet of Islam. Hijra in 622 becomes year 1 of the Muslim calendar."),
    (622, None, "politics", "Hijra to Medina", "Medina", 24.47, 39.61, "The umma becomes a political community."),
    (632, None, "death", "Death of Muhammad", "Medina", 24.47, 39.61, "Succession disputes begin almost immediately."),
    (634, 651, "war", "Arab-Muslim conquest of Persia and the Levant", "Yarmouk / Qadisiyyah", 32.70, 36.00, "Byzantium loses Syria and Egypt; the Sasanian state collapses."),
    (711, None, "war", "Muslim conquest of Visigothic Spain", "Guadalete, Spain", 36.6, -6.2, "Tariq ibn Ziyad crosses the strait that still bears a form of his name."),
    (732, None, "war", "Battle of Tours / Poitiers", "central France", 47.39, 0.68, "Frankish victory that later Europeans mythologized as a civilizational hinge."),
    (750, None, "politics", "Abbasid Revolution", "Kufa / Baghdad", 32.03, 44.40, "The caliphate's center of gravity moves east."),
    (800, None, "empire", "Charlemagne crowned emperor", "Rome", 41.89, 12.48, "A western empire in name, a Frankish one in fact."),
    (793, None, "war", "Viking raid on Lindisfarne", "Lindisfarne, England", 55.67, -1.80, "The Viking Age arrives in a monastery treasury."),
    (845, None, "war", "Vikings sack Paris", "Paris", 48.86, 2.35, "Ragnar's fleet on the Seine; the city pays Danegeld."),
    (868, None, "discovery", "Diamond Sutra printed in China", "Dunhuang, China", 40.14, 94.66, "Oldest dated complete printed book that survives."),
    (907, None, "empire", "Fall of the Tang dynasty", "Chang'an, China", 34.27, 108.95, "China fragments into the Five Dynasties."),
    (955, None, "war", "Battle of Lechfeld", "Augsburg, Germany", 48.37, 10.90, "Otto I breaks Magyar power in the west."),
    (960, 1279, "empire", "Song dynasty", "Kaifeng / Hangzhou", 34.80, 114.31, "Commerce, paper money, gunpowder, and a scholar-official elite."),
    (987, None, "politics", "Capetian dynasty begins in France", "Paris", 48.86, 2.35, "Hugh Capet. The line lasts, in one form or another, for centuries."),
    (1000, None, "discovery", "Norse at L'Anse aux Meadows", "Newfoundland", 51.60, -55.53, "Vinland: Europeans in the Americas five centuries before Columbus."),
    (1054, None, "politics", "Great Schism", "Constantinople / Rome", 41.01, 28.98, "Chalcedonian Christianity splits into Catholic and Orthodox churches."),
    (1066, None, "war", "Battle of Hastings", "Hastings, England", 50.91, 0.49, "Norman conquest of England."),
    (1071, None, "war", "Battle of Manzikert", "Malazgirt, Turkey", 39.14, 42.53, "Seljuk victory that opens Anatolia."),
    (1095, 1291, "war", "The Crusades", "Jerusalem / Levant", 31.78, 35.24, "Latin Christendom's wars for the Holy Land. Brutal, pious, and political."),
    (1099, None, "war", "Crusaders take Jerusalem", "Jerusalem", 31.78, 35.24, "A massacre that still stains the word crusade."),
    (1206, 1227, "empire", "Genghis Khan", "Mongolia / Eurasia", 47.92, 106.92, "The Mongol explosion. The largest contiguous land empire follows."),
    (1215, None, "politics", "Magna Carta", "Runnymede, England", 51.44, -0.57, "A peace treaty with barons that later becomes a liberty myth."),
    (1258, None, "war", "Mongols sack Baghdad", "Baghdad", 33.31, 44.37, "The Abbasid caliphate's city is ruined. Irrigation and libraries burn."),
    (1271, 1295, "discovery", "Marco Polo in Asia", "Venice / Khanbaliq", 39.90, 116.40, "A Venetian on the Mongol roads; Europe listens, not always accurately."),
    (1281, None, "calamity", "Kamikaze storms wreck the Mongol fleets", "Hakata Bay, Japan", 33.60, 130.40, "Typhoons, plus Japanese defense, save the islands twice."),
    (1300, 1521, "empire", "Aztec Empire", "Tenochtitlan", 19.43, -99.13, "A lake city and a tribute empire in the Valley of Mexico."),
    (1325, 1572, "empire", "Inca Empire", "Cusco, Peru", -13.52, -71.98, "Andean road-state from Ecuador to Chile."),
    (1337, 1453, "war", "Hundred Years' War", "Crécy / Agincourt / Orléans", 50.26, 1.88, "England and France. Joan of Arc, longbows, and a stronger French crown."),
    (1346, 1353, "calamity", "Black Death", "Mediterranean / Europe / Western Asia", 45.0, 10.0, "Bubonic plague kills perhaps a third of Europe. Labor, faith, and power all shift."),
    (1368, None, "empire", "Ming dynasty founded", "Nanjing, China", 32.06, 118.80, "Zhu Yuanzhang drives out the Mongol Yuan."),
    (1405, 1433, "discovery", "Zheng He's voyages", "Nanjing / Indian Ocean", 32.06, 118.80, "Ming treasure fleets to the Indian Ocean — then China turns inward."),
    (1438, None, "empire", "Inca Pachacuti remakes Cusco", "Cusco, Peru", -13.52, -71.98, "The imperial Inca state takes its classic form."),
    (1450, None, "discovery", "Gutenberg's press in Mainz", "Mainz, Germany", 50.00, 8.27, "Movable type in Europe. Scripture, science, and pamphlets explode."),
    (1453, None, "war", "Ottomans take Constantinople", "Constantinople", 41.01, 28.98, "Mehmed II. The Byzantine millennium ends; Istanbul begins."),
    (1469, 1539, "prophet", "Guru Nanak", "Punjab", 31.63, 74.87, "Founder of Sikhism."),
    (1492, None, "discovery", "Columbus reaches the Caribbean", "San Salvador / Bahamas", 24.08, -74.50, "A Genoese in Spanish pay. The Atlantic world — and catastrophe for the Americas — begins."),
    (1498, None, "discovery", "Vasco da Gama reaches India", "Calicut (Kozhikode)", 11.26, 75.78, "Portugal's sea route around Africa."),
    (1517, None, "politics", "Luther's Ninety-five Theses", "Wittenberg, Germany", 51.87, 12.65, "The Reformation. Europe splits, then multiplies."),
    (1519, 1521, "war", "Spanish-Aztec war", "Tenochtitlan", 19.43, -99.13, "Cortés, indigenous allies, and smallpox topple the Aztec Empire."),
    (1520, 1521, "calamity", "Smallpox in the Valley of Mexico", "Tenochtitlan", 19.43, -99.13, "A virgin-soil epidemic. Demographic collapse follows across the Americas."),
    (1526, None, "empire", "Mughal Empire founded", "Panipat, India", 29.39, 76.97, "Babur's victory. A Persianate empire in India."),
    (1532, 1572, "war", "Spanish-Inca war", "Cajamarca / Cusco", -7.16, -78.51, "Pizarro captures Atahualpa. Andes into the Spanish world."),
    (1543, None, "science", "Copernicus, On the Revolutions", "Frombork, Poland", 54.36, 19.68, "Earth is not the center. Published as he dies."),
    (1543, None, "death", "Death of Copernicus", "Frombork, Poland", 54.36, 19.68, "The book outlives the canon."),
    (1564, None, "birth", "William Shakespeare born", "Stratford-upon-Avon", 52.19, -1.71, "Baptized 26 April 1564."),
    (1588, None, "war", "Spanish Armada fails", "English Channel", 50.10, -1.80, "Storms and English gunnery. Spain remains a giant; the myth favors England."),
    (1600, None, "politics", "East India Company chartered", "London", 51.51, -0.09, "A company that will, in time, rule much of India."),
    (1603, None, "death", "Death of Elizabeth I", "Richmond, England", 51.46, -0.30, "Tudor age ends; Stuarts inherit a world power."),
    (1605, None, "culture", "Don Quixote, part one", "Madrid", 40.42, -3.70, "Cervantes invents the modern novel by laughing at chivalry."),
    (1607, None, "empire", "Jamestown founded", "Jamestown, Virginia", 37.21, -76.78, "First permanent English settlement in North America."),
    (1610, None, "science", "Galileo's telescopic discoveries", "Padua / Florence", 45.41, 11.88, "Jupiter's moons, a rugged Moon — the sky is not a perfect sphere."),
    (1616, None, "death", "Death of Shakespeare", "Stratford-upon-Avon", 52.19, -1.71, "Same date, in the old calendar, as Cervantes."),
    (1618, 1648, "war", "Thirty Years' War", "Central Europe", 50.08, 14.44, "A German catastrophe that redraws Europe's religious map."),
    (1632, None, "culture", "Taj Mahal construction begins", "Agra, India", 27.18, 78.04, "Shah Jahan's tomb for Mumtaz Mahal."),
    (1642, None, "birth", "Isaac Newton born", "Woolsthorpe, England", 52.81, -0.63, "Year of Galileo's death, in the old telling of science's relay."),
    (1642, 1651, "war", "English Civil Wars", "Naseby / London", 52.47, -0.99, "A king tried and killed by his own parliament."),
    (1644, None, "empire", "Qing conquest of Beijing", "Beijing", 39.90, 116.40, "Ming falls; Manchu Qing will rule until 1912."),
    (1665, 1666, "calamity", "Great Plague of London", "London", 51.51, -0.09, "Last major bubonic outbreak in England."),
    (1666, None, "calamity", "Great Fire of London", "London", 51.51, -0.09, "The medieval city burns; Wren's London rises."),
    (1683, None, "war", "Ottomans fail at Vienna", "Vienna", 48.21, 16.37, "High-water mark of Ottoman advance in Europe."),
    (1687, None, "science", "Newton's Principia", "London", 51.51, -0.09, "Gravity, motion, calculus in the world's toolkit."),
    (1692, None, "politics", "Salem witch trials", "Salem, Massachusetts", 42.52, -70.90, "A panic, then a shame, in colonial New England."),
    (1721, None, "empire", "Peter the Great, Emperor of Russia", "St. Petersburg", 59.93, 30.33, "A window on the Baltic and a forced modernization."),
    (1755, None, "calamity", "Lisbon earthquake", "Lisbon, Portugal", 38.72, -9.14, "All Saints' Day. Tsunami and fire. Voltaire writes about evil."),
    (1756, 1763, "war", "Seven Years' War", "Europe / India / Americas", 51.05, 13.74, "The first world war in all but name. Britain takes the inside track."),
    (1769, None, "birth", "Napoleon Bonaparte born", "Ajaccio, Corsica", 41.93, 8.74, "A minor noble on a newly French island."),
    (1776, None, "politics", "American Declaration of Independence", "Philadelphia", 39.95, -75.15, "A tax revolt writes a creed. The war is not yet won."),
    (1781, None, "science", "Uranus discovered by Herschel", "Bath, England", 51.38, -2.36, "The solar system gets bigger in a backyard telescope."),
    (1789, None, "politics", "French Revolution begins", "Paris", 48.86, 2.35, "Bastille, rights of man, then terror and a general."),
    (1793, None, "death", "Louis XVI executed", "Paris", 48.86, 2.35, "The sacred king becomes a citizen, then a corpse."),
    (1796, None, "science", "Jenner's smallpox vaccine", "Berkeley, England", 51.69, -2.46, "Cowpox against smallpox. The first vaccine."),
    (1799, None, "discovery", "Rosetta Stone found", "Rosetta (Rashid), Egypt", 31.40, 30.42, "The key to Egyptian hieroglyphs."),
    (1804, None, "empire", "Napoleon crowns himself emperor", "Paris", 48.86, 2.35, "Revolution eats its republic."),
    (1804, 1806, "discovery", "Lewis and Clark reach the Pacific", "Fort Clatsop, Oregon", 46.13, -123.88, "The United States looks west across a continent already inhabited."),
    (1807, None, "politics", "Britain abolishes the slave trade", "London", 51.51, -0.09, "The trade, not yet slavery itself. A long fight continues."),
    (1815, None, "war", "Battle of Waterloo", "Waterloo, Belgium", 50.68, 4.41, "Napoleon's last throw. Europe's conservative order follows."),
    (1815, None, "calamity", "Tambora eruption — the Year Without a Summer", "Sumbawa, Indonesia", -8.25, 117.99, "The largest recorded historic eruption. Harvests fail from Europe to North America."),
    (1817, 1892, "prophet", "Bahá'u'lláh", "Tehran / Acre", 35.69, 51.39, "Founder of the Bahá'í Faith."),
    (1821, 1832, "war", "Greek War of Independence", "Peloponnese / Missolonghi", 38.37, 21.83, "Ottoman Greece becomes a European cause."),
    (1830, None, "discovery", "First public steam railway, Liverpool–Manchester", "Manchester, England", 53.48, -2.24, "The railway age is no longer experimental."),
    (1833, None, "politics", "Britain abolishes slavery in the empire", "London", 51.51, -0.09, "Apprenticeship and compensation to owners — freedom with an invoice."),
    (1839, 1842, "war", "First Opium War", "Guangzhou / Nanjing", 23.13, 113.26, "Britain forces opium and ports on Qing China."),
    (1848, None, "politics", "Revolutions of 1848", "Paris / Vienna / Berlin / Budapest", 48.21, 16.37, "A spring of nations. Most of it is crushed by autumn."),
    (1848, None, "science", "Marx and Engels, Communist Manifesto", "London / Brussels", 51.51, -0.09, "A pamphlet that outlives the revolutions of its year."),
    (1853, 1856, "war", "Crimean War", "Sevastopol", 44.62, 33.53, "Modern war reporting, nursing, and a clumsy European concert."),
    (1857, 1858, "war", "Indian Rebellion", "Delhi / Lucknow / Kanpur", 28.65, 77.23, "The Company Raj ends; the British Crown takes India."),
    (1859, None, "science", "Darwin, On the Origin of Species", "London", 51.51, -0.09, "Natural selection. Biology after this is a different science."),
    (1861, 1865, "war", "American Civil War", "Gettysburg / Appomattox", 39.81, -77.23, "Union preserved; slavery abolished; 600,000 dead."),
    (1863, None, "politics", "Emancipation Proclamation", "Washington, D.C.", 38.90, -77.04, "A war measure that becomes a moral fact."),
    (1865, None, "death", "Abraham Lincoln assassinated", "Washington, D.C.", 38.90, -77.04, "Five days after Appomattox."),
    (1868, None, "politics", "Meiji Restoration", "Kyoto / Tokyo", 35.01, 135.77, "Japan chooses revolution from above and industrializes at speed."),
    (1869, None, "discovery", "Suez Canal opens", "Suez, Egypt", 30.59, 32.27, "Asia and Europe move weeks closer by sea."),
    (1870, 1871, "war", "Franco-Prussian War", "Sedan / Paris", 49.70, 4.94, "German unification in the Hall of Mirrors; a French wound."),
    (1876, None, "discovery", "Bell's telephone", "Boston", 42.36, -71.06, "A voice on a wire. The world shrinks again."),
    (1883, None, "calamity", "Krakatoa eruption", "Krakatoa, Indonesia", -6.10, 105.42, "The bang is heard thousands of kilometres away. Global sunsets follow."),
    (1885, None, "discovery", "Benz Patent-Motorwagen", "Mannheim, Germany", 49.49, 8.47, "The automobile, still a curiosity."),
    (1886, None, "politics", "Haymarket and the eight-hour fight", "Chicago", 41.88, -87.63, "Labor, dynamite, and a global May Day."),
    (1889, None, "birth", "Adolf Hitler born", "Braunau am Inn, Austria", 48.26, 13.04, "The 20th century's most destructive politician."),
    (1896, None, "culture", "First modern Olympic Games", "Athens", 37.97, 23.72, "Coubertin's revival, with ancient costume and modern nations."),
    (1898, None, "war", "Spanish–American War", "Manila / Santiago de Cuba", 14.60, 120.98, "Spain's empire ends; the U.S. acquires one."),
    (1903, None, "discovery", "Wright brothers fly", "Kitty Hawk, North Carolina", 36.02, -75.67, "Twelve seconds that unhook transport from the ground."),
    (1905, None, "science", "Einstein's annus mirabilis", "Bern, Switzerland", 46.95, 7.44, "Photons, Brownian motion, special relativity — a patent clerk."),
    (1905, None, "politics", "Bloody Sunday in St. Petersburg", "St. Petersburg", 59.93, 30.33, "The 1905 revolution; dress rehearsal for 1917."),
    (1911, None, "politics", "Xinhai Revolution", "Wuchang / Beijing", 30.58, 114.27, "China's last empire falls."),
    (1912, None, "calamity", "Titanic sinks", "North Atlantic", 41.73, -49.95, "The unsinkable lesson in class, ice, and radio."),
    (1914, 1918, "war", "First World War", "Western Front / global", 49.97, 2.30, "Industrial slaughter. Empires die; the influenza is coming."),
    (1917, None, "politics", "Russian Revolutions", "Petrograd", 59.93, 30.33, "Tsarism, then Kerensky, then Lenin. A 20th-century template."),
    (1918, 1920, "calamity", "Influenza pandemic of 1918", "Global", 41.0, -90.0, "More dead than the war in many counts. A virus in the trenches' wake."),
    (1918, None, "politics", "Armistice of 11 November", "Compiègne, France", 49.43, 2.91, "The guns stop at 11:00. The peace will not hold."),
    (1920, None, "politics", "Women's suffrage, U.S. 19th Amendment", "Washington, D.C.", 38.90, -77.04, "Half the republic, late to the vote."),
    (1922, None, "politics", "Mussolini's March on Rome", "Rome", 41.89, 12.48, "Fascism takes a state without winning a civil war."),
    (1928, None, "science", "Fleming notices penicillin", "London", 51.52, -0.13, "A mold that will, after much work, change infection."),
    (1929, None, "politics", "Wall Street crash", "New York", 40.71, -74.01, "The Depression goes global. Strongmen offer order."),
    (1931, None, "calamity", "China floods", "Yangtze / Huai", 32.0, 117.0, "Among the deadliest natural disasters recorded."),
    (1933, None, "politics", "Hitler becomes chancellor", "Berlin", 52.52, 13.41, "Democracy hands the keys to its assassin."),
    (1935, None, "science", "Radar developed in Britain", "Orford Ness, England", 52.09, 1.57, "The coming air war will not be blind."),
    (1937, None, "war", "Nanjing Massacre", "Nanjing, China", 32.06, 118.80, "Japanese capture of the Chinese capital. Mass killing of civilians."),
    (1939, 1945, "war", "Second World War", "Global", 52.23, 21.01, "Fifty million dead or more. The map, the bomb, and the UN follow."),
    (1941, None, "war", "Pearl Harbor", "Oahu, Hawaii", 21.36, -157.95, "The U.S. enters the world war it had tried to sit out."),
    (1941, 1945, "war", "The Holocaust", "Auschwitz / occupied Europe", 50.04, 19.18, "Industrial genocide of Jews, and mass murder of others, by Nazi Germany."),
    (1944, None, "war", "D-Day", "Normandy, France", 49.37, -0.87, "The Western Allies return to France."),
    (1945, None, "war", "Hiroshima and Nagasaki", "Hiroshima, Japan", 34.39, 132.46, "Nuclear weapons used in war. The age of mutual destruction begins."),
    (1945, None, "politics", "United Nations founded", "San Francisco", 37.77, -122.42, "A second try at a world organization, with the victors as policemen."),
    (1947, None, "politics", "Independence and Partition of India", "Lahore / Delhi / Calcutta", 28.61, 77.21, "Freedom and a refugee catastrophe in the same month."),
    (1948, None, "politics", "Israel declared; first Arab–Israeli war", "Tel Aviv / Jerusalem", 32.08, 34.78, "A state for the Jews; displacement for Palestinians. The conflict is not over."),
    (1948, None, "death", "Gandhi assassinated", "New Delhi", 28.60, 77.21, "The independence saint shot by a Hindu nationalist."),
    (1949, None, "politics", "People's Republic of China proclaimed", "Beijing", 39.90, 116.40, "Mao on Tiananmen. The most populous revolution."),
    (1950, 1953, "war", "Korean War", "Korean Peninsula", 38.00, 127.00, "Cold War, hot peninsula. The border still sits near where it began."),
    (1953, None, "science", "Structure of DNA published", "Cambridge, England", 52.21, 0.12, "Watson, Crick, Franklin's data. Biology becomes information."),
    (1954, None, "politics", "Brown v. Board of Education", "Washington, D.C.", 38.90, -77.04, "U.S. school segregation ruled unconstitutional."),
    (1955, None, "death", "Einstein dies", "Princeton, New Jersey", 40.36, -74.67, "The century's physicist. His last equation is unfinished."),
    (1957, None, "space", "Sputnik 1", "Baikonur, Kazakhstan", 45.92, 63.34, "A beep from orbit. The space age is public."),
    (1961, None, "space", "Yuri Gagarin orbits Earth", "Baikonur / Earth orbit", 45.92, 63.34, "A human being looks down on the whole planet at once."),
    (1962, None, "war", "Cuban Missile Crisis", "Cuba / Washington / Moscow", 23.13, -82.38, "The closest brush with nuclear war. Thirteen days."),
    (1963, None, "death", "John F. Kennedy assassinated", "Dallas, Texas", 32.78, -96.81, "Televised grief. Conspiracy culture is born in the same hour."),
    (1964, None, "politics", "Civil Rights Act (U.S.)", "Washington, D.C.", 38.90, -77.04, "Law against Jim Crow. Enforcement is another war."),
    (1966, 1976, "politics", "Cultural Revolution", "Beijing / China", 39.90, 116.40, "Mao's last revolution. Schools, temples, and lives wrecked."),
    (1968, None, "death", "Martin Luther King Jr. assassinated", "Memphis, Tennessee", 35.13, -90.05, "The American prophet of nonviolence, shot on a motel balcony."),
    (1969, None, "space", "Apollo 11 lands on the Moon", "Sea of Tranquility / Houston", 0.67, 23.47, "A species steps onto another world. Half a billion watch."),
    (1973, None, "politics", "Chile coup", "Santiago, Chile", -33.45, -70.67, "Allende dead; Pinochet's dictatorship. The Cold War in a palace."),
    (1975, None, "war", "Fall of Saigon", "Ho Chi Minh City", 10.82, 106.63, "The Vietnam War ends with helicopters on a roof."),
    (1979, None, "politics", "Iranian Revolution", "Tehran", 35.69, 51.39, "A shah out, an Islamic Republic in. Oil and ideology."),
    (1979, 1989, "war", "Soviet–Afghan War", "Kabul / Hindu Kush", 34.53, 69.17, "The USSR's Vietnam. Blowback will last decades."),
    (1980, 1988, "war", "Iran–Iraq War", "Shatt al-Arab", 30.45, 48.17, "A million dead. Chemical weapons. No winner worth the name."),
    (1986, None, "calamity", "Chernobyl disaster", "Pripyat, Ukraine", 51.39, 30.10, "A reactor lid in the sky. The word 'exclusion zone' enters Europe."),
    (1989, None, "politics", "Berlin Wall opens", "Berlin", 52.52, 13.41, "A night of hammers. The Cold War's scenery collapses."),
    (1989, None, "politics", "Tiananmen Square", "Beijing", 39.90, 116.40, "A protest, then tanks. China chooses markets without the ballot."),
    (1990, 1991, "war", "Gulf War", "Kuwait / southern Iraq", 29.38, 47.99, "A coalition, satellites, and a 100-hour ground war."),
    (1991, None, "politics", "Soviet Union dissolved", "Moscow", 55.75, 37.62, "Fifteen countries where one superpower stood."),
    (1994, None, "war", "Rwandan genocide", "Kigali, Rwanda", -1.94, 30.06, "About 800,000 Tutsi and others murdered in ~100 days."),
    (1994, None, "politics", "South African majority-rule election", "Pretoria / Johannesburg", -25.75, 28.19, "Mandela president. Apartheid legally ends."),
    (1997, None, "science", "Dolly the sheep cloned", "Edinburgh, Scotland", 55.95, -3.19, "A mammal from a differentiated cell. Ethics catches up slowly."),
    (2001, None, "war", "September 11 attacks", "New York / Washington / Pennsylvania", 40.71, -74.01, "Al-Qaeda. Two towers, a war on terror, and a long occupation of Afghanistan."),
    (2003, None, "war", "U.S.-led invasion of Iraq", "Baghdad", 33.31, 44.37, "WMD claims collapse. Insurgency does not."),
    (2004, None, "calamity", "Indian Ocean earthquake and tsunami", "Aceh / Indian Ocean", 3.32, 95.85, "A magnitude-9 undersea quake. ~230,000 dead from Indonesia to Africa."),
    (2008, None, "politics", "Global financial crisis", "New York / worldwide", 40.71, -74.01, "Lehman weekend. A generation's trust in finance cracks."),
    (2008, None, "politics", "Barack Obama elected U.S. president", "Chicago / Washington", 41.88, -87.63, "The first Black president of the United States."),
    (2010, None, "calamity", "Haiti earthquake", "Port-au-Prince", 18.54, -72.34, "A shallow urban quake. Hundreds of thousands die; the recovery is still unfinished."),
    (2011, None, "politics", "Arab Spring", "Tunis / Cairo / Benghazi / Damascus", 30.04, 31.24, "Uprisings. A few transitions, a war in Syria, a restored strongman in Egypt."),
    (2011, None, "death", "Osama bin Laden killed", "Abbottabad, Pakistan", 34.15, 73.22, "A raid that does not end the wars 9/11 started."),
    (2011, None, "calamity", "Tōhoku earthquake, tsunami, and Fukushima", "Sendai / Fukushima, Japan", 38.27, 140.87, "Magnitude 9.0. A nuclear plant's triple meltdown."),
    (2014, None, "war", "Russia annexes Crimea; war in Donbas begins", "Crimea / Donetsk", 44.95, 34.10, "The post-Cold-War European map is forced open."),
    (2014, None, "calamity", "West African Ebola epidemic", "Guinea / Liberia / Sierra Leone", 8.48, -13.23, "Urban Ebola. Thousands dead; a rehearsal for later pandemics."),
    (2015, None, "politics", "Paris climate agreement", "Paris", 48.86, 2.35, "Almost every country signs. Delivery is another story."),
    (2016, None, "politics", "Brexit referendum", "United Kingdom", 51.51, -0.09, "Leave wins. A decades-long European marriage goes to court."),
    (2019, 2023, "calamity", "COVID-19 pandemic", "Wuhan / global", 30.59, 114.30, "A novel coronavirus. Millions dead, then a scramble for vaccines and truth."),
    (2021, None, "space", "James Webb Space Telescope launches", "French Guiana / L2", 5.24, -52.77, "Infrared eyes on the early universe."),
    (2022, None, "war", "Russia's full-scale invasion of Ukraine", "Kyiv / Kharkiv / Kherson", 50.45, 30.52, "The largest European war since 1945. Cities under artillery; a nuclear state as aggressor."),
    (2023, None, "war", "Israel–Hamas war after 7 October", "Gaza / southern Israel", 31.50, 34.47, "Mass killing of civilians on both sides of the fence. A humanitarian catastrophe in Gaza."),
    (2023, None, "calamity", "Turkey–Syria earthquakes", "Kahramanmaraş, Turkey", 37.58, 36.93, "A pair of huge quakes on the East Anatolian Fault. Tens of thousands dead."),
    (2024, None, "politics", "Largest election year on record", "India / US / Indonesia / EU / Mexico", 28.61, 77.21, "Billions vote. Democracies strain; several hold."),
    (2025, None, "calamity", "Los Angeles wildfires (early 2025)", "Los Angeles, California", 34.05, -118.24, "Urban-interface fire in a megacity. A climate-century signature."),
    (2026, None, "live", "World Desk comes online", "Your browser", 30.27, -97.74, "A public-data globe trying to hold live coverage and five millennia on one timeline."),

    # Hindu religion, saints, and gurus. Many lifetimes are traditional;
    # Shankara's century is the usual scholarly 8th c. CE, not the 5th c. BCE
    # of some matha lists.
    (-1500, -1200, "culture", "Early Vedic hymns take shape", "Sapta Sindhu / Punjab", 31.15, 75.34, "The Rigveda is compiled over centuries. Foundational Sanskrit scripture of Hindu tradition.", True),
    (-800, -500, "culture", "Principal Upanishads", "northern India", 25.32, 83.01, "Forest dialogues on atman and brahman. Later Vedanta reads them as scripture."),
    (-599, -527, "prophet", "Mahavira (traditional Jain dates)", "Vaishali / Pavapuri", 26.00, 85.13, "24th Tirthankara of Jainism in the traditional chronology.", True),
    (-400, -200, "culture", "Bhagavad Gita takes written form", "northern India", 26.45, 80.33, "Krishna and Arjuna on dharma. The Mahabharata's most traveled book.", True),
    (500, 800, "saint", "Bhakti of the Tamil Alvars and Nayanars", "Tamil country", 10.79, 79.14, "Vaishnava and Shaiva poet-saints. Temple Hinduism in the Tamil voice."),
    (700, None, "saint", "Andal (traditional)", "Srivilliputhur, Tamil Nadu", 9.51, 77.63, "The woman Alvar. Tiruppavai still sung in Margazhi.", True),
    (788, 820, "saint", "Adi Shankaracharya", "Kalady, Kerala", 10.17, 76.44, "Advaita Vedanta. Mathas at Sringeri, Dwaraka, Puri, and Jyotirmath. Traditional dates 788–820 CE; some lineages place him much earlier.", True),
    (788, None, "birth", "Birth of Adi Shankaracharya (traditional)", "Kalady, Kerala", 10.17, 76.44, "Born on the Periyar. The 8th-century dating is the common scholarly one.", True),
    (820, None, "death", "Death of Adi Shankaracharya (traditional)", "Kedarnath, Himalaya", 30.73, 79.07, "Tradition has him leave the body at Kedarnath still a young man.", True),
    (820, None, "culture", "Four amnaya mathas associated with Shankara", "Sringeri, Karnataka", 13.42, 75.25, "Sringeri, Dwaraka, Puri, Jyotirmath — seats that still argue Vedanta."),
    (788, 820, "saint", "Mandana Mishra / Sureshvara (traditional debate)", "Mahishi / north India", 25.85, 86.93, "The famous debate story of Shankara and the Mimamsa household. Hagiography, not a dated dispatch.", True),
    (1017, 1137, "saint", "Ramanujacharya", "Sriperumbudur, Tamil Nadu", 12.97, 79.94, "Vishishtadvaita. Temple, grace, and a qualified non-dual Brahman."),
    (1106, 1167, "saint", "Basavanna", "Basavakalyan, Karnataka", 17.87, 76.95, "Sharana movement. Vachanas, the ishtalinga, and a critique of caste."),
    (1130, 1160, "saint", "Akkamahadevi (approximate)", "Udutadi / Kalyana", 14.17, 75.40, "Veerashaiva poet-saint. Shiva as Chennamallikarjuna.", True),
    (1238, 1317, "saint", "Madhvacharya", "Pajaka / Udupi, Karnataka", 13.34, 74.74, "Dvaita Vedanta. Krishna at Udupi; a dualist reading of the sutras."),
    (1275, 1296, "saint", "Sant Dnyaneshwar", "Alandi, Maharashtra", 18.68, 73.90, "Jnaneshwari on the Gita, in Marathi. He is said to enter sanjeevan samadhi at 21."),
    (1270, 1350, "saint", "Namdev (approximate)", "Pandharpur, Maharashtra", 17.68, 75.33, "Varkari poet of Vitthal. Verses later travel into the Guru Granth Sahib.", True),
    (1290, 1380, "saint", "Vedanta Desika (approximate)", "Kanchipuram / Srirangam", 12.86, 79.32, "Post-Ramanuja Sri Vaishnava acharya. Poet, logician, temple theologian.", True),
    (1440, 1518, "saint", "Kabir", "Varanasi", 25.32, 83.01, "Weaver-poet. Ram and Rahim in the same doha; later claimed by more than one panth."),
    (1479, 1531, "saint", "Vallabhacharya", "Champaranya / Mathura", 26.75, 83.67, "Shuddhadvaita and the Pushtimarg. Krishna as the child of grace."),
    (1482, 1565, "saint", "Surdas (approximate)", "Braj / Mathura", 27.50, 77.68, "Blind poet of Krishna in Braj Bhasha. Tradition more than a firm biography.", True),
    (1486, 1534, "saint", "Chaitanya Mahaprabhu", "Nabadwip, Bengal", 23.41, 88.37, "Gaudiya Vaishnavism. Public kirtan; Krishna-bhakti as a mass path."),
    (1498, 1546, "saint", "Mirabai", "Merta / Mewar, Rajasthan", 26.65, 74.03, "Rajput princess, Krishna's devotee. Bhajans that outlive the court."),
    (1500, 1600, "saint", "Purandara Dasa (approximate)", "Hampi / Karnataka", 15.34, 76.46, "Karnataka bhakti and the pedagogy of Carnatic music.", True),
    (1532, 1623, "saint", "Tulsidas", "Rajapur / Varanasi", 25.32, 83.01, "Ramcharitmanas. Rama in Awadhi for a north Indian public."),
    (1540, 1603, "saint", "Eknath", "Paithan, Maharashtra", 19.48, 75.38, "Varkari saint. Marathi Ramayana and a householder's bhakti."),
    (1608, 1649, "saint", "Tukaram", "Dehu, Maharashtra", 18.72, 73.75, "Abhangs to Vitthal. The voice of the Varkari road to Pandharpur."),
    (1608, 1681, "saint", "Samarth Ramdas", "Sajjangad, Maharashtra", 17.65, 73.91, "Dasbodh. Guru to a generation that includes Shivaji in later telling."),
    (1761, 1830, "saint", "Swaminarayan (Sahajanand Swami)", "Chhapaiya / Gadhada, Gujarat", 26.98, 82.39, "Reformer-guru of a still-growing sampradaya."),
    (1836, 1886, "saint", "Ramakrishna Paramahamsa", "Dakshineswar, Bengal", 22.66, 88.36, "Kali's priest at Dakshineswar. Many paths, one realization — as his disciples told it."),
    (1836, None, "birth", "Birth of Ramakrishna", "Kamarpukur, Bengal", 23.23, 87.73, "A village birth; a Calcutta temple will make the name."),
    (1863, 1902, "saint", "Swami Vivekananda", "Kolkata / Belur Math", 22.63, 88.35, "Chicago 1893. Vedanta and yoga enter a global vocabulary."),
    (1863, None, "birth", "Birth of Vivekananda", "Kolkata", 22.54, 88.35, "Narendranath Datta. Later the monk who speaks in Chicago."),
    (1872, 1950, "saint", "Sri Aurobindo", "Kolkata / Pondicherry", 11.93, 79.83, "Revolutionary, then yogi. Integral yoga and an ashram on the Coromandel."),
    (1879, 1950, "saint", "Ramana Maharshi", "Tiruvannamalai, Tamil Nadu", 12.23, 79.07, "Who am I? Silence as teaching at Arunachala."),
    (1836, 1918, "saint", "Sai Baba of Shirdi", "Shirdi, Maharashtra", 19.77, 74.48, "Fakir-saint of a mosque-temple town. Still a pan-Indian pilgrimage."),
    (1896, 1982, "saint", "Anandamayi Ma", "Kheora / Dehradun", 23.95, 91.11, "Bengali woman saint. Devotees took her presence as the teaching."),
    (1884, 1963, "saint", "Swami Sivananda", "Rishikesh", 30.12, 78.31, "Divine Life Society. A 20th-century exporter of yoga and Vedanta."),
    (1893, 1994, "saint", "Chandrashekarendra Saraswati (Kanchi Paramacharya)", "Kanchipuram", 12.84, 79.70, "68th Shankaracharya of the Kanchi Kamakoti peetham in that matha's count."),
    (1916, 1993, "saint", "Swami Chinmayananda", "Ernakulam / Mumbai", 9.97, 76.28, "Chinmaya Mission. Gita classes for a middle-class republic."),
    (1897, None, "culture", "Ramakrishna Mission founded", "Belur Math, Bengal", 22.63, 88.35, "Vivekananda's order: service as worship."),
    (1893, None, "culture", "Vivekananda at the Parliament of Religions", "Chicago", 41.87, -87.62, "Sisters and brothers of America. A Hindu monk on a world's-fair stage."),
]

# Indian kingdoms, Muhammad's life in more detail, Brahma Kumaris, and
# major artifacts. Still a desk of recorded landmarks — not every dispatch.
EXTRA = [
    # ── Muhammad and the first community ────────────────────────────────
    (570, None, "birth", "Birth of Muhammad (traditional)", "Mecca", 21.42, 39.83, "Year of the Elephant in the sira. Orphaned young; later a trusted merchant of Quraysh.", True),
    (595, None, "politics", "Muhammad marries Khadija (traditional)", "Mecca", 21.42, 39.83, "The first believer in later Islamic telling. A trading partnership that becomes a household.", True),
    (610, None, "prophet", "First revelation in the Cave of Hira", "Jabal al-Nour, near Mecca", 21.46, 39.85, "Iqra. The Qur'an begins as recited speech, not a bound book.", True),
    (613, None, "prophet", "Public preaching in Mecca begins (traditional)", "Mecca", 21.42, 39.83, "From a private circle to the Haram. Quraysh opposition hardens.", True),
    (619, None, "death", "Year of Sorrow: Khadija and Abu Talib die", "Mecca", 21.42, 39.83, "Wife and uncle gone in one year. Protection in Mecca thins.", True),
    (620, None, "prophet", "Isra and Mi'raj (traditional)", "Jerusalem / Mecca", 31.78, 35.24, "Night journey in the sira. Later tied to the Rock in Jerusalem.", True),
    (622, None, "politics", "Constitution of Medina", "Medina", 24.47, 39.61, "A written pact among emigrants, helpers, and some Jewish tribes. Politics of a new town."),
    (624, None, "war", "Battle of Badr", "Badr, Hejaz", 23.78, 38.79, "A small caravan fight that the early community remembers as a sign."),
    (625, None, "war", "Battle of Uhud", "Mount Uhud, Medina", 24.50, 39.61, "A reverse. Archers leave the slope; the Prophet is wounded in the tradition."),
    (627, None, "war", "Battle of the Trench", "Medina", 24.47, 39.61, "A confederate siege. The ditch and a storm; Medina holds."),
    (628, None, "politics", "Treaty of Hudaybiyyah", "Hudaybiyyah, near Mecca", 21.44, 39.63, "A ten-year truce that later Muslim historians call a clear victory."),
    (630, None, "war", "Conquest of Mecca", "Mecca", 21.42, 39.83, "The city opens with little fighting. Idols of the Kaaba are removed in the sira."),
    (632, None, "prophet", "Farewell sermon and Hajj", "Mount Arafat / Mecca", 21.35, 39.98, "A last public address in the tradition. Death follows in Medina the same year.", True),
    (632, 661, "empire", "Rashidun Caliphate", "Medina / Kufa", 24.47, 39.61, "Abu Bakr, Umar, Uthman, Ali. Expansion, the first written Qur'an mushaf, then fitna."),
    (656, 661, "war", "First Fitna", "Basra / Siffin / Kufa", 30.51, 47.78, "Civil war after Uthman's killing. The community splits in ways that still name sects."),
    (661, 750, "empire", "Umayyad Caliphate", "Damascus", 33.51, 36.29, "A dynasty in Syria. Arabic as administration; the Dome of the Rock."),
    (691, None, "artifact", "Dome of the Rock completed", "Jerusalem", 31.78, 35.24, "An Umayyad shrine on the Temple Mount. Mosaic and octagon."),
    (750, 1258, "empire", "Abbasid Caliphate", "Baghdad", 33.31, 44.37, "The round city, paper, and a long twilight after 1258."),

    # ── Indian kingdoms ────────────────────────────────────────────────
    (-544, -413, "empire", "Haryanka / early Magadha", "Rajgir, Bihar", 25.03, 85.42, "Bimbisara and Ajatashatru. The Gangetic state that later empires inherit.", True),
    (-345, -322, "empire", "Nanda Empire", "Pataliputra", 25.61, 85.14, "Mahapadma's Magadha. Greek writers later call it a great army on the Ganga."),
    (-322, -185, "empire", "Maurya Empire", "Pataliputra (Patna)", 25.61, 85.14, "Chandragupta, Bindusara, Ashoka. The first pan-Indian state we can really map."),
    (-268, -232, "politics", "Ashoka's reign", "Pataliputra / Dhauli", 20.19, 85.84, "Kalinga, then dhamma on stone. Edicts from Kandahar to Karnataka."),
    (-261, None, "war", "Kalinga War", "Dhauli / Odisha", 20.19, 85.84, "Ashoka's conversion story begins in a massacre. The edicts say so themselves."),
    (-185, -73, "empire", "Shunga kingdom", "Pataliputra / Vidisha", 23.53, 77.81, "Post-Maurya Magadha. Bharhut and early Sanchi stone."),
    (-230, 220, "empire", "Satavahana kingdom", "Paithan / Amaravati", 19.48, 75.38, "Deccan trade, Prakrit, and the Amaravati stupa world."),
    (30, 375, "empire", "Kushan Empire", "Peshawar / Mathura", 34.01, 71.57, "Kanishka's realm on the Silk Road. Buddha in stone with a Roman echo."),
    (127, None, "politics", "Kanishka (approximate accession)", "Purushapura (Peshawar)", 34.01, 71.57, "The Kushan high point. Dates move; the gold coins do not.", True),
    (250, 500, "empire", "Vakataka kingdom", "Nandivardhana / Ajanta", 20.55, 75.70, "Deccan patrons of Ajanta's later caves."),
    (275, 897, "empire", "Pallava kingdom", "Kanchipuram", 12.84, 79.70, "Shore temple, granite rathas, and a southern Sanskrit court."),
    (320, 550, "empire", "Gupta Empire", "Pataliputra / Ujjain", 23.18, 75.78, "Kalidasa's century in later memory. Zero, temples, and a classical north."),
    (543, 753, "empire", "Early Chalukyas of Badami", "Badami, Karnataka", 15.92, 75.68, "Deccan temple-caves and a check on Harsha in the south."),
    (606, 647, "empire", "Harsha's kingdom", "Kannauj", 27.05, 79.92, "A north Indian court Xuanzang actually visited."),
    (650, 1250, "empire", "Eastern Chalukyas / Vengi", "Rajahmundry / Vengi", 16.99, 81.78, "Andhra between bigger neighbours."),
    (730, 1036, "empire", "Gurjara-Pratihara", "Kannauj / Ujjain", 27.05, 79.92, "One leg of the tripartite fight for the Ganga plain."),
    (750, 1161, "empire", "Pala Empire", "Bengal / Bihar / Vikramashila", 25.25, 87.28, "Buddhist palaeography, Nalanda's last great patrons."),
    (753, 982, "empire", "Rashtrakuta Empire", "Manyakheta, Karnataka", 17.22, 77.21, "Kailasa at Ellora cut downward from a cliff."),
    (848, 1279, "empire", "Chola Empire", "Thanjavur", 10.79, 79.14, "Rajaraja and Rajendra. Bronze, navy, and a temple-state."),
    (985, 1014, "politics", "Rajaraja I", "Thanjavur", 10.79, 79.14, "Brihadisvara rises. The imperial Chola machine."),
    (1014, 1044, "politics", "Rajendra I and the Gangaikonda city", "Gangaikonda Cholapuram", 11.21, 79.45, "A northern raid remembered in a new capital's name."),
    (1000, 1346, "empire", "Hoysala kingdom", "Halebidu / Belur", 13.21, 75.99, "Soapstone temples, star-plans, and a late-Deccan court."),
    (1163, 1323, "empire", "Kakatiya kingdom", "Warangal", 17.98, 79.60, "Telugu uplands, granite, and a fall to the Delhi Sultanate."),
    (1187, 1317, "empire", "Yadavas of Devagiri", "Daulatabad, Maharashtra", 19.94, 75.21, "Marathi court before the sultanate takes the fort."),
    (1190, 1311, "empire", "Pandyas of Madurai (imperial revival)", "Madurai", 9.93, 78.12, "Pearl, temple, and a second Pandya high tide."),
    (1206, 1526, "empire", "Delhi Sultanate", "Delhi", 28.65, 77.23, "Mamluk, Khalji, Tughlaq, Sayyid, Lodi. Persian in the Yamuna plain."),
    (1228, 1826, "empire", "Ahom kingdom", "Charaideo / Sivasagar, Assam", 26.94, 94.88, "Six centuries in the Brahmaputra valley. Mughals do not keep Assam."),
    (1336, 1646, "empire", "Vijayanagara Empire", "Hampi, Karnataka", 15.34, 76.46, "A Hindu imperial city on the Tungabhadra. Stones still stand in ranks."),
    (1347, 1527, "empire", "Bahmani Sultanate", "Gulbarga / Bidar", 17.91, 77.52, "Deccan Islamicate courts that later split into five sultanates."),
    (1526, 1707, "empire", "Mughal high period (Babur to Aurangzeb)", "Agra / Delhi / Fatehpur Sikri", 27.18, 78.02, "A Timurid house in India. Farmans, painting, and a peafowl throne."),
    (1556, 1605, "politics", "Akbar's reign", "Fatehpur Sikri / Agra", 27.09, 77.66, "Expansion, sulh-i-kul, and a new capital on a ridge."),
    (1628, 1658, "politics", "Shah Jahan", "Agra / Shahjahanabad", 27.18, 78.02, "Taj Mahal, the Red Fort, and a marble idea of kingship."),
    (1658, 1707, "politics", "Aurangzeb's reign", "Delhi / Deccan", 19.94, 75.21, "The empire's widest map and its most expensive wars."),
    (1674, None, "empire", "Shivaji crowned Chhatrapati", "Raigad, Maharashtra", 18.23, 73.45, "A Maratha state with forts for bones."),
    (1674, 1818, "empire", "Maratha confederacy", "Pune / Satara", 18.52, 73.86, "From a hill kingdom to a confederacy the British must bargain with."),
    (1565, None, "war", "Battle of Talikota", "Talikota / Rakkasagi, Karnataka", 16.48, 76.31, "Deccan sultanates break Vijayanagara. Hampi is sacked."),
    (1761, None, "war", "Third Battle of Panipat", "Panipat, Haryana", 29.39, 76.97, "Abdali smashes a Maratha army. North India opens again."),
    (1761, 1799, "empire", "Mysore under Haidar Ali and Tipu", "Srirangapatna", 12.42, 76.69, "Rockets, a tiger, and four wars with the Company."),
    (1799, None, "war", "Siege of Seringapatam; death of Tipu", "Srirangapatna", 12.42, 76.69, "The Company takes Mysore. A stuffed tiger later sits in London."),
    (1799, 1849, "empire", "Sikh Empire of Ranjit Singh", "Lahore", 31.55, 74.34, "A Punjab kingdom between Afghans and the Company."),
    (1729, 1949, "empire", "Travancore kingdom (modern high tide)", "Thiruvananthapuram", 8.52, 76.94, "A Kerala state that outlasts many bigger names, into independent India."),
    (1326, 1956, "empire", "Mewar / Udaipur", "Chittorgarh / Udaipur", 24.89, 74.65, "A Rajput house that writes its own long memory of sieges."),

    # ── Brahma Kumaris ─────────────────────────────────────────────────
    (1876, None, "birth", "Birth of Dada Lekhraj (Brahma Baba)", "Hyderabad, Sindh", 25.39, 68.37, "Later Prajapita Brahma. A jeweller before the visions."),
    (1936, 1937, "saint", "Om Mandli / Brahma Kumaris founded", "Hyderabad, Sindh", 25.39, 68.37, "Lekhraj's satsang becomes a women-led community. Colonial Sindh, then Partition."),
    (1950, None, "saint", "Brahma Kumaris settle at Mount Abu (Madhuban)", "Mount Abu, Rajasthan", 24.59, 72.72, "Headquarters after Sindh. Raja yoga as a daily drill."),
    (1969, None, "death", "Death of Brahma Baba", "Mount Abu, Rajasthan", 24.59, 72.72, "Leadership stays with the Dadis. The movement goes abroad in the next decades."),
    (1922, 2007, "saint", "Dadi Prakashmani", "Mount Abu, Rajasthan", 24.59, 72.72, "Administrative head after Brahma Baba. UN NGO years."),
    (1916, 2020, "saint", "Dadi Janki", "Mount Abu / London", 24.59, 72.72, "The public face of Brahma Kumaris in the West for a generation."),
    (1980, None, "politics", "Brahma Kumaris as a UN NGO (approximate)", "New York / Mount Abu", 40.75, -73.97, "Peace conferences and a meditation brand at the UN campus.", True),

    # ── Artifacts and monuments ────────────────────────────────────────
    (-2500, None, "artifact", "Dancing Girl bronze, Mohenjo-daro", "Mohenjo-daro", 27.32, 68.14, "Lost-wax bronze. A teenage stance from the Indus streets."),
    (-2500, None, "artifact", "Pashupati / proto-Shiva seal", "Mohenjo-daro", 27.32, 68.14, "A horned figure in yogic seat. Later Hindu eyes read a god into it."),
    (-2500, None, "artifact", "Priest-King steatite bust", "Mohenjo-daro", 27.32, 68.14, "Trefoil robe, broken at the body. The face of the Indus in every textbook."),
    (-1750, None, "artifact", "Code of Hammurabi stele", "Susa / Babylon (now Louvre)", 32.54, 44.42, "Basalt law in the round. Shamash dictating to a king."),
    (-1336, -1327, "artifact", "Tutankhamun's tomb goods", "Valley of the Kings", 25.74, 32.60, "A minor pharaoh, an intact burial. The mask is the 20th century's Egypt."),
    (-1250, None, "artifact", "Standard of Ur", "Ur, Mesopotamia", 30.96, 46.10, "War and peace in lapis and shell. A box that is a city."),
    (-650, None, "artifact", "Cyrus Cylinder", "Babylon (now British Museum)", 32.54, 44.42, "A Persian king on a Babylonian barrel. Later read as a human-rights text."),
    (-500, None, "artifact", "Behistun Inscription", "Bisitun, Iran", 34.39, 45.40, "Darius in three languages on a cliff. The cuneiform Rosetta."),
    (-250, None, "artifact", "Ashoka lion capital, Sarnath", "Sarnath, Uttar Pradesh", 25.38, 83.02, "Four lions, a wheel. Independent India's emblem."),
    (-250, None, "artifact", "Ashokan pillars and edicts", "Lauriya Nandangarh / throughout", 26.99, 84.40, "Polished sandstone with a voice. Dhamma as public letter."),
    (-113, None, "artifact", "Heliodorus pillar", "Vidisha, Madhya Pradesh", 23.53, 77.81, "A Greek ambassador calls himself Bhagavata. Vishnu in an inscription."),
    (100, 200, "artifact", "Didarganj Yakshi", "Patna, Bihar", 25.61, 85.14, "Chunar sandstone, polish like metal. A woman who is not a goddess and is."),
    (400, 650, "artifact", "Ajanta cave paintings", "Ajanta, Maharashtra", 20.55, 75.70, "Jataka in pigment. Torches found them again in 1819."),
    (400, 700, "artifact", "Iron Pillar of Delhi", "Mehrauli, Delhi", 28.52, 77.19, "Wrought iron that barely rusts. A Gupta-period boast still standing."),
    (600, 900, "artifact", "Ellora Kailasa temple (Cave 16)", "Ellora, Maharashtra", 20.03, 75.18, "A mountain subtracted until a temple remained."),
    (850, 1250, "artifact", "Chola Nataraja bronzes", "Thanjavur / Chidambaram", 11.40, 79.69, "Shiva as cosmic dancer. Lost-wax, four arms, a ring of fire."),
    (1000, None, "artifact", "Brihadisvara temple fabric", "Thanjavur", 10.78, 79.13, "Granite vimana. A king's name in the stone as much as in copper plates."),
    (1100, 1250, "artifact", "Angkor Wat", "Angkor, Cambodia", 13.41, 103.87, "Vishnu's house in later Buddhist keeping. The largest religious monument."),
    (1200, None, "artifact", "Qutb Minar and iron pillar court", "Mehrauli, Delhi", 28.52, 77.19, "A victory tower over reused temple stone. Sultanate Delhi's first skyline."),
    (1230, 1260, "artifact", "Sun Temple, Konark", "Konark, Odisha", 19.89, 86.09, "A stone chariot of Surya. Wheels that are calendars."),
    (1250, None, "artifact", "Borobudur in later ruin and recovery", "Central Java", -7.61, 110.20, "A Mahayana mountain of stone. British and Dutch 'discovery' is a second life."),
    (1632, 1653, "artifact", "Taj Mahal", "Agra", 27.18, 78.04, "Mumtaz's tomb. White marble as a Mughal sentence."),
    (1639, 1648, "artifact", "Peacock Throne (original)", "Delhi / later Iran", 28.66, 77.24, "Jewels as furniture. Nader Shah will take it in 1739."),
    (-196, None, "artifact", "Rosetta Stone carved", "Memphis / later Rashid", 31.40, 30.42, "Priestly decree in three scripts. Champollion's later key."),
    (100, None, "artifact", "Antikythera mechanism (wreck date approx.)", "Antikythera, Greece", 35.87, 23.30, "Bronze gears for the sky. Recovered from a wreck in 1901.", True),
    (220, None, "artifact", "Terracotta Army (First Emperor's tomb complex)", "Lintong, Xi'an", 34.38, 109.27, "Thousands of fired soldiers. Dug up by farmers in 1974."),
    (1947, None, "artifact", "Dead Sea Scrolls first found", "Qumran / Dead Sea", 31.74, 35.46, "Jars in a cave. Hebrew Bible centuries older on paper."),
    (1739, None, "war", "Nader Shah sacks Delhi; Koh-i-Noor leaves with the loot", "Delhi", 28.65, 77.23, "The Peacock Throne and the diamond enter the Iranian then Sikh then British story."),
]

CATS = {
    "calamity": "Natural calamities",
    "war": "Wars & conflict",
    "prophet": "Prophets & founders",
    "saint": "Saints & gurus",
    "artifact": "Artifacts & monuments",
    "birth": "Famous births",
    "death": "Famous deaths",
    "discovery": "Exploration & firsts",
    "empire": "Empires & cities",
    "politics": "Politics & law",
    "science": "Science",
    "culture": "Culture",
    "space": "Space",
    "live": "Live coverage",
}

def main():
    events = []
    for i, row in enumerate(RAW + EXTRA):
        traditional = False
        if len(row) == 9:
            year, year_end, category, title, place, lat, lon, summary, traditional = row
        else:
            year, year_end, category, title, place, lat, lon, summary = row
        slug = "".join(ch if ch.isalnum() else "-" for ch in title.lower())
        slug = "-".join(filter(None, slug.split("-")))[:48]
        events.append({
            "id": f"{category}-{year}-{slug}",
            "year": year,
            "yearEnd": year_end,
            "category": category,
            "title": title,
            "place": place,
            "lat": round(lat, 4),
            "lon": round(lon, 4),
            "summary": summary,
            "traditional": bool(traditional),
            "source": "Standard historical chronology; traditional religious dates flagged.",
        })
    events.sort(key=lambda e: (e["year"], e["title"]))
    payload = {
        "title": "World Desk",
        "subtitle": "Five thousand years of recorded events, plus a live public-news cache.",
        "eraStart": -3000,
        "eraEnd": 2026,
        "disclaimer": "This is a desk of major recorded events, not a complete newscast and not a verdict. Religious lifetimes — including many Hindu gurus — use traditional dates. Live pins are outlet-country coverage, not verified incidents.",
        "categories": [{"id": k, "label": v} for k, v in CATS.items()],
        "events": events,
    }
    root = Path(__file__).resolve().parents[1]
    targets = [
        root / "src/data/local_data/world_desk_events.json",
        root / "public/world-desk/events.json",
    ]
    text = json.dumps(payload, ensure_ascii=False, indent=2)
    for path in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text + "\n", encoding="utf-8")
        print(f"{path} ({len(events)} events)")

if __name__ == "__main__":
    main()
