#!/usr/bin/env bash
# Build a double-clickable macOS app bundle for God's Eye View.
#
#   npm run app:mac              # -> dist-app/God's Eye View.app
#   npm run app:mac -- --install # also copies it into ~/Applications
#
# The bundle is a thin launcher: it starts the dev server through
# scripts/dev-fresh.sh (Keychain + .env key resolution, cache clear), waits
# for the port, then opens the app in a chromeless browser window. The
# loading screen inside the app then runs the /api/health roster.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

APP_NAME="God's Eye View"
BUNDLE_ID="com.godseyeview.launcher"
OUT_DIR="${ROOT_DIR}/dist-app"
APP_DIR="${OUT_DIR}/${APP_NAME}.app"
INSTALL=0
for arg in "$@"; do
  case "$arg" in
    --install) INSTALL=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: macOS app bundles can only be built on macOS" >&2
  exit 1
fi

# Prefer the keg-only Homebrew node@24 the project requires.
for candidate in /opt/homebrew/opt/node@24/bin /usr/local/opt/node@24/bin; do
  [[ -d "$candidate" ]] && export PATH="${candidate}:${PATH}"
done
NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]]; then
  echo "error: node not found; install node@24 (brew install node@24)" >&2
  exit 1
fi
NODE_DIR="$(dirname "$NODE_BIN")"

echo "Rendering icon..."
node scripts/build-app-icon.mjs "${OUT_DIR}/icon"

echo "Assembling ${APP_DIR}"
rm -rf "$APP_DIR"
mkdir -p "${APP_DIR}/Contents/MacOS" "${APP_DIR}/Contents/Resources"
cp "${OUT_DIR}/icon/AppIcon.icns" "${APP_DIR}/Contents/Resources/AppIcon.icns"

cat > "${APP_DIR}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>$(node -p "require('./package.json').version")</string>
  <key>CFBundleShortVersionString</key><string>$(node -p "require('./package.json').version")</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSApplicationCategoryType</key><string>public.app-category.utilities</string>
</dict>
</plist>
PLIST

# The launcher bakes in the checkout path and node directory at build time so
# the bundle keeps working after it is copied to /Applications.
cat > "${APP_DIR}/Contents/MacOS/launch" <<LAUNCH
#!/usr/bin/env bash
# God's Eye View launcher (generated by scripts/build-mac-app.sh)
set -uo pipefail

GEV_ROOT="${ROOT_DIR}"
NODE_DIR="${NODE_DIR}"
APP_NAME="${APP_NAME}"
LAUNCH

cat >> "${APP_DIR}/Contents/MacOS/launch" <<'LAUNCH'
export PATH="${NODE_DIR}:/opt/homebrew/bin:/usr/local/bin:${PATH}"
PORT="${PORT:-4173}"
URL="http://localhost:${PORT}/"
LOG_DIR="${GEV_ROOT}/.gev-logs"
LOG="${LOG_DIR}/app-launch.log"
mkdir -p "${LOG_DIR}"

fail() {
  local msg="$1"
  local tail_text
  tail_text="$(tail -n 12 "${LOG}" 2>/dev/null | sed "s/\"/'/g" || true)"
  /usr/bin/osascript -e "display dialog \"${msg}\n\nLog: ${LOG}\n\n${tail_text}\" with title \"${APP_NAME}\" buttons {\"OK\"} default button 1 with icon stop" >/dev/null 2>&1 || true
  exit 1
}

server_up() {
  curl -fsS -m 2 -o /dev/null "${URL}" 2>/dev/null
}

open_window() {
  # Chromeless app window when a Chromium browser is installed; otherwise the
  # default browser. `open -n` hands the flags to a running instance too.
  for browser in "Google Chrome" "Chromium" "Brave Browser" "Microsoft Edge" "Arc"; do
    if [[ -d "/Applications/${browser}.app" || -d "${HOME}/Applications/${browser}.app" ]]; then
      open -n -a "${browser}" --args --app="${URL}" --new-window && return 0
    fi
  done
  open "${URL}"
}

if [[ ! -d "${GEV_ROOT}" ]]; then
  fail "Checkout not found at ${GEV_ROOT}. Rebuild the app with: npm run app:mac"
fi
cd "${GEV_ROOT}" || fail "Cannot enter ${GEV_ROOT}"

if server_up; then
  echo "[$(date '+%F %T')] server already up; opening window" >> "${LOG}"
  open_window
  exit 0
fi

if ! command -v node >/dev/null 2>&1; then
  fail "node not found. Install Node 24: brew install node@24"
fi

echo "[$(date '+%F %T')] starting dev server on :${PORT}" >> "${LOG}"
# dev-fresh.sh resolves keys (env > .env > Keychain), clears the Vite cache,
# and execs Vite. It stays alive after this launcher exits.
PORT="${PORT}" nohup ./scripts/dev-fresh.sh >> "${LOG}" 2>&1 &
SERVER_PID=$!

# Wait for the port. dev-fresh exits early (missing Maps key etc.), so watch
# the pid as well as the socket.
for _ in $(seq 1 120); do
  if server_up; then
    echo "[$(date '+%F %T')] server ready" >> "${LOG}"
    open_window
    exit 0
  fi
  if ! kill -0 "${SERVER_PID}" 2>/dev/null; then
    fail "The dev server exited before it was ready."
  fi
  sleep 0.5
done
fail "Timed out waiting for ${URL} (60 s). The server may still be starting; check the log."
LAUNCH
chmod +x "${APP_DIR}/Contents/MacOS/launch"

# Refresh the icon cache entry Finder keeps for this path.
touch "$APP_DIR"

echo "Built: ${APP_DIR}"
if [[ "$INSTALL" == "1" ]]; then
  mkdir -p "${HOME}/Applications"
  rm -rf "${HOME}/Applications/${APP_NAME}.app"
  cp -R "$APP_DIR" "${HOME}/Applications/"
  echo "Installed: ${HOME}/Applications/${APP_NAME}.app (drag it to the Dock)"
fi
