// functions/api/openai/hud-summary.js
/**
 * `/api/openai/hud-summary` — Cloudflare Pages Function.
 *
 * Production counterpart of the dev middleware in `vite.config.js`
 * (openAiRealtimeProxy). The browser's Intel HUD posts a small scene-context
 * JSON document and gets back a five-word summary generated by the OpenAI
 * Responses API. Without this Function the static deployment answered 405 and
 * the HUD logged "[HUD] AI summary unavailable".
 *
 * Contract (identical to dev):
 *   POST { ...context }            → 200 { summary, error: null }
 *   missing OPENAI_API_KEY        → 503 { error: 'OPENAI_API_KEY is not set' }
 *   non-POST                      → 405 { error: 'Method not allowed' }
 *   oversized/invalid body        → 400 { error }
 *   upstream/config failure       → upstream status or 502 { error }
 *
 * Env: OPENAI_API_KEY (required), OPENAI_HUD_SUMMARY_MODEL (optional),
 *      GEV_RATELIMIT_OPENAI_PER_MIN (optional, requests/min/IP).
 */
import {
  HUD_SUMMARY_INSTRUCTIONS,
  OPENAI_HUD_SUMMARY_MODEL_DEFAULT,
  extractOpenAiResponseText,
  toFiveWordHudSummary,
} from '../../../src/voice/realtimeSession.js';
import {
  allowRequest,
  createCachedOptInLimiter,
  jsonResponse,
  methodNotAllowed,
  rateLimitedResponse,
  readJsonBody,
} from '../../_lib.js';

/** The dev middleware caps the context document at 64 KB. */
const HUD_SUMMARY_MAX_BODY_BYTES = 64 * 1024;

/** Built once per isolate and reused, so the per-IP window state persists. */
const openAiLimiter = createCachedOptInLimiter();

export async function onRequest(context) {
  const { env, request } = context;

  if (request.method !== 'POST') return methodNotAllowed();

  // Opt-in per-IP throttle (GEV_RATELIMIT_OPENAI_PER_MIN). No-op when unset.
  if (!allowRequest(openAiLimiter(env.GEV_RATELIMIT_OPENAI_PER_MIN), request)) {
    return rateLimitedResponse();
  }

  const apiKey = env.OPENAI_API_KEY;
  if (!apiKey) {
    return jsonResponse({ error: 'OPENAI_API_KEY is not set' }, { status: 503 });
  }

  const body = await readJsonBody(request, HUD_SUMMARY_MAX_BODY_BYTES);
  if (!body.ok) return jsonResponse({ error: body.error }, { status: body.status });

  try {
    const response = await fetch('https://api.openai.com/v1/responses', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: env.OPENAI_HUD_SUMMARY_MODEL || OPENAI_HUD_SUMMARY_MODEL_DEFAULT,
        instructions: HUD_SUMMARY_INSTRUCTIONS.join(' '),
        input: JSON.stringify(body.value),
        reasoning: { effort: 'minimal' },
        max_output_tokens: 100,
      }),
    });
    const data = await response.json().catch(() => ({}));
    const summary = toFiveWordHudSummary(extractOpenAiResponseText(data));
    return jsonResponse(
      {
        summary: summary || null,
        error: response.ok ? null : data.error?.message || 'OpenAI HUD summary request failed',
      },
      { status: response.ok && summary ? 200 : response.status || 502, cacheControl: 'no-store' },
    );
  } catch (error) {
    return jsonResponse(
      { error: error?.message || 'OpenAI HUD summary request failed' },
      { status: 502 },
    );
  }
}
